### ISSUE TITLE
endpoint bug.

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/sherpa-ncnn#120]
Hi @csukuangfj , does the number 4 here stands for downsampling factor? Should be 2 if the model is `zipformer` which downsampling factor is 2 ?
https://github.com/k2-fsa/sherpa-ncnn/blob/1a6bca6c138f058b1e3a5a1d76028567ded440c6/sherpa-ncnn/csrc/modified-beam-search-decoder.cc#L215

**Comment by csukuangfj** [comment]
> does the number 4 here stands for downsampling factor?

Yes, you are right.

---

> Should be 2 if the model is zipformer which downsampling factor is 2 ?

No. The downsampling factor of zipformer is also 4.

The related code is given below:

There are two places where downsampling happens.

(1)
https://github.com/k2-fsa/icefall/blob/c51e6c5b9c8e4d92b9e810e26202c3b3b633c519/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py#L326
```python3
        self.encoder_embed = Conv2dSubsampling(
            num_features, encoder_dims[0], dropout=dropout
        )
```

The downsampling factor for the first time is 2

(2)
https://github.com/k2-fsa/icefall/blob/c51e6c5b9c8e4d92b9e810e26202c3b3b633c519/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py#L564
```python3
        x = self.downsample_output(x)
        # class Downsample has this rounding behavior..
        assert self.output_downsampling_factor == 2, self.output_downsampling_factor
```

The second downsampling factor is also 2.

So the total downsampling factor is `2*2 = 4`.

---

Hint:
https://github.com/k2-fsa/icefall/blob/c51e6c5b9c8e4d92b9e810e26202c3b3b633c519/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py#L511
```python3
        lengths = (x_lens - 7) >> 1
```

https://github.com/k2-fsa/icefall/blob/c51e6c5b9c8e4d92b9e810e26202c3b3b633c519/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer.py#L567
```python3
        lengths = (lengths + 1) >> 1
```

**Comment by kobenaxie** [comment]
oh, thanks for your reply~

**Comment by csukuangfj** [comment]
@kobenaxie 
By the way, are you interested in https://github.com/k2-fsa/sherpa-onnx ?

We have a lot of open issues listed at
https://github.com/k2-fsa/sherpa-onnx/issues

It would be great if you can contribute.
