### ISSUE TITLE
aarch64运行报错：layer MemoryData not exists or registered Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by busisiji** [k2-fsa/sherpa-ncnn#121]
0 tegra-hda: HDMI 0 (hw:0,3), ALSA (0 in, 2 out)
   1 tegra-snd-t210ref-mobile-rt565x: - (hw:1,0), ALSA (16 in, 16 out)
   2 tegra-snd-t210ref-mobile-rt565x: - (hw:1,1), ALSA (16 in, 16 out)
   3 tegra-snd-t210ref-mobile-rt565x: - (hw:1,2), ALSA (16 in, 16 out)
   4 tegra-snd-t210ref-mobile-rt565x: - (hw:1,3), ALSA (16 in, 16 out)
   5 tegra-snd-t210ref-mobile-rt565x: - (hw:1,4), ALSA (16 in, 16 out)
   6 tegra-snd-t210ref-mobile-rt565x: - (hw:1,5), ALSA (16 in, 16 out)
   7 tegra-snd-t210ref-mobile-rt565x: - (hw:1,6), ALSA (16 in, 16 out)
   8 tegra-snd-t210ref-mobile-rt565x: - (hw:1,7), ALSA (16 in, 16 out)
   9 tegra-snd-t210ref-mobile-rt565x: - (hw:1,8), ALSA (16 in, 16 out)
  10 tegra-snd-t210ref-mobile-rt565x: - (hw:1,9), ALSA (16 in, 16 out)
  11 hdmi, ALSA (0 in, 2 out)
  12 pulse, ALSA (32 in, 32 out)
  13 music, ALSA (0 in, 128 out)
* 14 default, ALSA (32 in, 32 out)
Use default device: default
Started! Please speak
layer MemoryData not exists or registered
Segmentation fault (core dumped)
在window上可以正常使用

**Comment by busisiji** [comment]
USB Audio Device: - (hw:2,0), ALSA (1 in, 2 out)

**Comment by csukuangfj** [comment]
你用的是最新的代码么？

如果你以前有 拉取过 sherpa-ncnn, 请先把以前的 build 目录，先删掉，然后再重新编译。

**Comment by busisiji** [comment]
我没有编译，而是直接导入库
import sys

try:
    import sounddevice as sd
except ImportError as e:
    print("Please install sounddevice first. You can use")
    print()
    print("  pip install sounddevice")
    print()
    print("to install it")
    sys.exit(-1)

import sherpa_ncnn


def create_recognizer():
    # Please replace the model files if needed.
    # See https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/index.html
    # for download links.
    recognizer = sherpa_ncnn.Recognizer(
        tokens="sherpa-ncnn-lstm-transducer-small-2023-02-13/tokens.txt",
        encoder_param="sherpa-ncnn-lstm-transducer-small-2023-02-13/encoder_jit_trace-pnnx.ncnn.param",
        encoder_bin="sherpa-ncnn-lstm-transducer-small-2023-02-13/encoder_jit_trace-pnnx.ncnn.bin",
        decoder_param="sherpa-ncnn-lstm-transducer-small-2023-02-13/decoder_jit_trace-pnnx.ncnn.param",
        decoder_bin="sherpa-ncnn-lstm-transducer-small-2023-02-13/decoder_jit_trace-pnnx.ncnn.bin",
        joiner_param="sherpa-ncnn-lstm-transducer-small-2023-02-13/joiner_jit_trace-pnnx.ncnn.param",
        joiner_bin="sherpa-ncnn-lstm-transducer-small-2023-02-13/joiner_jit_trace-pnnx.ncnn.bin",
        num_threads=4,
        decoding_method="modified_beam_search",
        enable_endpoint_detection=True,
        rule1_min_trailing_silence=2.4,
        rule2_min_trailing_silence=1.2,
        rule3_min_utterance_length=300,

    )
    print(recognizer)
    return recognizer


def main():
    try:
        print("Started! Please speak")
        recognizer = create_recognizer()
        sample_rate = recognizer.sample_rate
        samples_per_read = int(0.1 * sample_rate)  # 0.1 second = 100 ms
        last_result = ""
        with sd.InputStream(channels=1, dtype="float32", samplerate=sample_rate) as s:
            while True:
                samples, _ = s.read(samples_per_read)  # a blocking read
                samples = samples.reshape(-1)
                recognizer.accept_waveform(sample_rate, samples)
                result = recognizer.text
                if last_result != result:
                    last_result = result
                    print(result)
    except Exception as e:
        print(e)


if __name__ == "__main__":
    devices = sd.query_devices()
    print(devices)
    default_input_device_idx = sd.default.device[0]
    print(f'Use default device: {devices[default_input_device_idx]["name"]}')

    try:
        main()
    except KeyboardInterrupt:
        print("\nCaught Ctrl + C. Exiting")

**Comment by busisiji** [comment]
我是直接pip install  sherpa-ncnn安装的

**Comment by csukuangfj** [comment]
> 我是直接pip install sherpa-ncnn安装的

什么时候安装的呢？安装的是最新版本么

**Comment by csukuangfj** [comment]
> aarch64运行报错

你是 aarch64 平台， pip install 的安装包，应该只提供 x86 和 x86_64 的.

你可以参考
- https://k2-fsa.github.io/sherpa/ncnn/python/index.html#method-2
- https://k2-fsa.github.io/sherpa/ncnn/python/index.html#method-3
- https://k2-fsa.github.io/sherpa/ncnn/python/index.html#method-4

在 aarch64 平台本地编译

**Comment by busisiji** [comment]
已经安装了，但运行时报错
sherpa-ncnn                   1.2

**Comment by busisiji** [comment]
本地编译aarch64-linux-gnu-gcc -v报错：
-bash: /home/nvidia/software/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc: cannot execute binary file: Exec format error

**Comment by csukuangfj** [comment]
> 你是 aarch64 平台， pip install 的安装包，应该只提供 x86 和 x86_64 的.

<img width="963" alt="Screenshot 2023-02-21 at 15 41 54" src="https://user-images.githubusercontent.com/5284924/220279707-a110964a-6c30-4b02-b5c7-5b8cc53442cb.png">


请使用 最新版 . 1.2 太低了.

**Comment by csukuangfj** [comment]
> 本地编译aarch64-linux-gnu-gcc -v报错： -bash: /home/nvidia/software/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc: cannot execute binary file: Exec format error


交叉编译的意思是, 在 x86_64 平台编译，然后把 编译好的 binary, copy 到 aarch64 运行。

你是直接在 aarch64 平台编译，不需要采用交叉编译。

请参考
https://k2-fsa.github.io/sherpa/ncnn/install/linux.html

你直接使用 aarch64 平台提供的 gcc 就好了

**Comment by busisiji** [comment]
可以了，非常感谢

**Comment by csukuangfj** [comment]
> 可以了，非常感谢

👍 

https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/index.html

这里有很多 pre-trained models, 欢迎尝试。
