### ISSUE TITLE
aarch64下运行程序，语音识别会有3秒左右的延迟：Don't Use GPU. has_gpu: 0, config.use_vulkan_compute: 0

### ISSUE THREAD

**Issue by busisiji** [k2-fsa/sherpa-ncnn#122]
![微信图片_20230222095542](https://user-images.githubusercontent.com/92677771/220501050-d95fbb1e-96a1-4294-a95f-f9984b792e22.jpg)

**Comment by busisiji** [comment]
怎么使用GPU?

**Comment by csukuangfj** [comment]
> aarch64下运行程序，语音识别会有3秒左右的延迟

1. 你用的是哪个模型？
2. 你说的延迟，是指启动程序需要3秒？ 还是指，启动后，从说话到输出识别结果，有3秒的延迟？

**Comment by csukuangfj** [comment]
> 怎么使用GPU?

我们使用的 是 ncnn, 只支持 通过 vulkan 去使用 gpu.

默认编译时，不使用 vulkan.

你可以参考
https://github.com/k2-fsa/sherpa-ncnn/blob/master/build-android-arm64-v8a-with-vulkan.sh
去支持 嵌入式板子上的 vulkan.

**Comment by busisiji** [comment]
启动后，从说话到输出识别结果，有3秒的延迟

**Comment by csukuangfj** [comment]
你用的是哪个模型？

运行的具体参数是什么呢？

---

如果你希望得到更详细的帮助，请回答完整的问题。谢谢

**Comment by busisiji** [comment]
sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13

**Comment by busisiji** [comment]
![Uploading 微信图片_20230222104140.jpg…]()

**Comment by busisiji** [comment]
![微信图片_20230222104140](https://user-images.githubusercontent.com/92677771/220507625-660373eb-d8d9-4137-b9e1-90254afb2a47.jpg)

**Comment by csukuangfj** [comment]
你可以先用这个命令
https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#id2
去测一下，在这块板子上，这个模型的 RTF 么？

---

https://www.bilibili.com/video/BV1p54y1P7Be
这个是同类模型，在 iPhone 上的效果。

这个模型期望的延时，应该在0.4秒左右。 我还没碰到过有3秒延时的情况。

**Comment by busisiji** [comment]
-bash: ./build/bin/sherpa-ncnn: No such file or directory

**Comment by busisiji** [comment]
![微信图片_20230222111001](https://user-images.githubusercontent.com/92677771/220511622-0bcf6778-b75e-4bb4-a151-3a95e7c4b840.jpg)

**Comment by busisiji** [comment]
构建 sherpa-ncnn失败

**Comment by csukuangfj** [comment]
这个是网络问题。

重试几次？

---

重试若干次，直到成功。

**Comment by busisiji** [comment]
不行

**Comment by csukuangfj** [comment]
这个是你网络的问题。只有重试。

----

还有，你可以手动下载那个 repo, 然后改下那个编译脚本。

**Comment by busisiji** [comment]
不行，https://github.com/alsa-project/alsa-lib我在window上也法进去或者git clone,应该不是我网的问题，毕竟我可以进来这个网站，可能是https://github.com/alsa-project/alsa-lib出了问题

**Comment by busisiji** [comment]
不行，https://github.com/alsa-project/alsa-lib我在window上也法进去或者git clone,应该不是我网的问题，毕竟我可以进来这个网站，可能是https://github.com/alsa-project/alsa-lib出了问题

**Comment by busisiji** [comment]
可以进去，但无法git clone

**Comment by csukuangfj** [comment]
你直接下载这个，然后解压

https://github.com/alsa-project/alsa-lib/archive/refs/heads/master.zip

**Comment by csukuangfj** [comment]
需要修改点代码，你看看那个 build script, 应该很容易改的。

**Comment by busisiji** [comment]
![微信图片_20230222162310](https://user-images.githubusercontent.com/92677771/220563433-952ac205-415e-4a34-b9c3-8813ed9e264d.jpg)
![微信图片_20230222162206](https://user-images.githubusercontent.com/92677771/220563451-1e7f0ef8-7119-4f60-82a9-b5e3a322ed1c.jpg)

**Comment by busisiji** [comment]
重命名alsa-lib.zip也不行

**Comment by busisiji** [comment]
哦，要解压

**Comment by csukuangfj** [comment]
@busisiji 

这个问题解决了吗？
