### ISSUE TITLE
[Help wanted] sherpa-ncnn for android crash when using LSTM model

### ISSUE THREAD

**Issue by spianmo** [k2-fsa/sherpa-ncnn#125]
#### 如何在安卓平台的sherpa-ncnn Demo中使用LSTM模型？

**描述：**

当我只是修改对应的`ModelConfig`时，修改部分代码如下方附录代码，`sherpa-ncnn App`闪退，看起来是在`jni`中`Java_com_k2fsa_sherpa_ncnn_SherpaNcnn_new`中调用`sherpa_ncnn::Model::Create`创建`sherpa_ncnn::LstmModel::LstmModel`时出现的问题。

**推测：**

是我在使用`LSTM`模型时必须要如下示图2中`LOGE`所述，添加`SherpaMetaData` 到`encoder_xxx.ncnn.param`中吗？我应该如何添加`SherpaMetaData`？

**崩溃日志：**

![image](https://user-images.githubusercontent.com/18194268/220971371-da3823b4-4363-4d84-9ac0-059764573f38.png)

![image](https://user-images.githubusercontent.com/18194268/220971390-9ef7d894-f666-4248-97af-ab9611d67ed4.png)

**以下是我修改的`SherpaNcnn.kt`部分代码：**

```kotlin
fun getModelConfig(type: Int, useGPU: Boolean): ModelConfig? {
    when (type) {
        //crash
        1 -> {
            val modelDir = "sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13"
            return ModelConfig(
                encoderParam = "$modelDir/encoder_jit_trace-pnnx.ncnn.param",
                encoderBin = "$modelDir/encoder_jit_trace-pnnx.ncnn.bin",
                decoderParam = "$modelDir/decoder_jit_trace-pnnx.ncnn.param",
                decoderBin = "$modelDir/decoder_jit_trace-pnnx.ncnn.bin",
                joinerParam = "$modelDir/joiner_jit_trace-pnnx.ncnn.param",
                joinerBin = "$modelDir/joiner_jit_trace-pnnx.ncnn.bin",
                tokens = "$modelDir/tokens.txt",
                numThreads = 4,
                useGPU = useGPU,
            )
        }
        2 -> {
            val modelDir = "sherpa-ncnn-conv-emformer-transducer-2022-12-08/v2"
            return ModelConfig(
                encoderParam = "$modelDir/encoder_jit_trace-pnnx-epoch-15-avg-3.ncnn.param",
                encoderBin = "$modelDir/encoder_jit_trace-pnnx-epoch-15-avg-3.ncnn.bin",
                decoderParam = "$modelDir/decoder_jit_trace-pnnx-epoch-15-avg-3.ncnn.param",
                decoderBin = "$modelDir/decoder_jit_trace-pnnx-epoch-15-avg-3.ncnn.bin",
                joinerParam = "$modelDir/joiner_jit_trace-pnnx-epoch-15-avg-3.ncnn.param",
                joinerBin = "$modelDir/joiner_jit_trace-pnnx-epoch-15-avg-3.ncnn.bin",
                tokens = "$modelDir/tokens.txt",
                numThreads = 4,
                useGPU = useGPU,
            )
        }
        //crash
        3 -> {
            val modelDir = "sherpa-ncnn-lstm-transducer-small-2023-02-13"
            return ModelConfig(
                encoderParam = "$modelDir/encoder_jit_trace-pnnx.ncnn.param",
                encoderBin = "$modelDir/encoder_jit_trace-pnnx.ncnn.bin",
                decoderParam = "$modelDir/decoder_jit_trace-pnnx.ncnn.param",
                decoderBin = "$modelDir/decoder_jit_trace-pnnx.ncnn.bin",
                joinerParam = "$modelDir/joiner_jit_trace-pnnx.ncnn.param",
                joinerBin = "$modelDir/joiner_jit_trace-pnnx.ncnn.bin",
                tokens = "$modelDir/tokens.txt",
                numThreads = 4,
                useGPU = useGPU,
            )
        }
    }
    return null
}
```

**Comment by csukuangfj** [comment]
你的模型，是最新的吗？

**Comment by spianmo** [comment]
> 

对的，在huggingface上下的最新的

**Comment by spianmo** [comment]
> 你的模型，是最新的吗？
通过GIT_LFS拉取的最新的模型
- sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13
- sherpa-ncnn-lstm-transducer-small-2023-02-13

**Comment by spianmo** [comment]
ModelConfig里面指定的文件路径都对过了，模型是昨天晚上git lfs下的

**Comment by spianmo** [comment]
huggingface链接是从sherpa官网主页找到的，[https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/index.html](https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/index.html)

**Comment by csukuangfj** [comment]
你用的是 lstm 模型。你对比下你本地的文件，是不是和
https://huggingface.co/marcoyang/sherpa-ncnn-lstm-transducer-small-2023-02-13/blob/main/encoder_jit_trace-pnnx.ncnn.param

这个文件一样的？

![Screenshot 2023-02-24 at 14 22 45](https://user-images.githubusercontent.com/5284924/221107300-bedfdf4f-8e3c-40dc-9046-fe3c0d637a18.png)

**Comment by spianmo** [comment]
> https://huggingface.co/marcoyang/sherpa-ncnn-lstm-transducer-small-2023-02-13/blob/main/encoder_jit_trace-pnnx.ncnn.param

重新下载并对比了，是有的，so是拉的最新的sherpa jni代码在Mac上编译的，问题依旧存在。

```
git lfs install
git clone https://huggingface.co/marcoyang/sherpa-ncnn-lstm-transducer-small-2023-02-13
```
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18194268/221117655-a4b05734-df0e-4486-afff-6d738f5ada0f.png">

**Comment by spianmo** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/18194268/221118285-545bca43-b2f9-43db-819c-a933ad8111a6.png">

**Comment by spianmo** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18194268/221118522-5e31040a-2fb6-41af-a24a-6f20127d2f89.png">

**Comment by csukuangfj** [comment]
能检查下，你的 jniLibs/arm64-v8a 里面的 so, 是你最新编译的么？

**Comment by spianmo** [comment]
> 能检查下，你的 jniLibs/arm64-v8a 里面的 so, 是你最新编译的么？

我检查一下，大概晚一些回复

**Comment by spianmo** [comment]
> 能检查下，你的 jniLibs/arm64-v8a 里面的 so, 是你最新编译的么？

刚刚编译了一版，代码master分支的，build-android-arm64-v8a-with-vulkan.sh，带vulkan的版本，问题还是存在

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18194268/221157819-6a7e03d3-36c5-47c1-b82e-c8c7c03cfbe5.png">

**Comment by spianmo** [comment]
> 能检查下，你的 jniLibs/arm64-v8a 里面的 so, 是你最新编译的么？

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/18194268/221158817-c9f69fa6-5780-4c8a-9c18-af3b258ce1ce.png">

**Comment by csukuangfj** [comment]
我本地试 非 vulkan 的版本，是没问题的 (可以加载模型，并且打开界面， lstm 模型的识别，现在应该有点问题， 可能是更新 ncnn 导致的)

你试的 conv-emformer 或者 zipformer 会有问题么.

**Comment by csukuangfj** [comment]
注意: 你上面截图中

1. 你 build 的 lib, 在 xxx-vulkan 那个目录
2. 但是，你 copy 的时候，没有copy xxx-vulkan 那个目录下的 lib

**Comment by csukuangfj** [comment]
请再次确认下，你是不是用的最新的 .so

你虽然用的是最新的代码，并且也生成了 so, 但是，你的 android, 可能用的并不是你现在生成的 so .

**Comment by spianmo** [comment]
> 请再次确认下，你是不是用的最新的 .so
> 
> 你虽然用的是最新的代码，并且也生成了 so, 但是，你的 android, 可能用的并不是你现在生成的 so .

抱歉，真的是so的问题，sherpa-ncnn项目很早就关注了，应该是那时候jni编译的缓存，so也确实拷错了，现在我清除了编译缓存重新编译拷贝so之后LSTM模型能加载，能进页面，但是目前识别好像确实是有问题，不返回识别结果；随后我尝试使用了sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13模型，模型创建成功，但是在识别阶段如下图报了一个`ncnn::VkMat::create`的错误，但是这应该就是ncnn的问题了。

目前使用sherpa-ncnn-conv-emformer-transducer系列模型都没有问题，lstm模型和zipformer都有问题（就目前测试而言），我的初衷是想比较一下各种模型在智能眼镜等嵌入式安卓设备上的识别准确率和推理速度，然后选择一个效果较好的模型作为离线语音指令的核心能力，会持续关注sherpa-ncnn，感谢作者的付出。

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18194268/221234748-784d0585-3fd5-45e0-aa95-943a089809b9.png">

**Comment by spianmo** [comment]
希望后续可以解决lstm模型和zipformer模型在sherpa-ncnn-android上的问题

**Comment by spianmo** [comment]
> 我本地试 非 vulkan 的版本，是没问题的 (可以加载模型，并且打开界面， lstm 模型的识别，现在应该有点问题， 可能是更新 ncnn 导致的)
> 
> 你试的 conv-emformer 或者 zipformer 会有问题么.

LSTM模型能加载，能进页面，但是目前不吐推理结果。
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/18194268/221238236-3fca05ef-7be0-4344-8b33-24c25e2bdc81.png">

**Comment by csukuangfj** [comment]
> > 请再次确认下，你是不是用的最新的 .so
> 
> > 
> 
> > 你虽然用的是最新的代码，并且也生成了 so, 但是，你的 android, 可能用的并不是你现在生成的 so .
> 
> 
> 
> 抱歉，真的是so的问题，sherpa-ncnn项目很早就关注了，应该是那时候jni编译的缓存，so也确实拷错了，现在我清除了编译缓存重新编译拷贝so之后LSTM模型能加载，能进页面，但是目前识别好像确实是有问题，不返回识别结果；随后我尝试使用了sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13模型，模型创建成功，但是在识别阶段如下图报了一个`ncnn::VkMat::create`的错误，但是这应该就是ncnn的问题了。
> 
> 
> 
> 目前使用sherpa-ncnn-conv-emformer-transducer系列模型都没有问题，lstm模型和zipformer都有问题（就目前测试而言），我的初衷是想比较一下各种模型在智能眼镜等嵌入式安卓设备上的识别准确率和推理速度，然后选择一个效果较好的模型作为离线语音指令的核心能力，会持续关注sherpa-ncnn，感谢作者的付出。
> 
> 
> 
> <img width="1728" alt="image" src="https://user-images.githubusercontent.com/18194268/221234748-784d0585-3fd5-45e0-aa95-943a089809b9.png">
> 
> 

你试试cpu 版本的zipformer?

**Comment by spianmo** [comment]
> 

OK，我试试

**Comment by csukuangfj** [comment]
> > 
> 
> 
> 
> OK，我试试

试zipformer 或者conv-emformer.

**Comment by spianmo** [comment]
> > > 
> > 
> > 
> > OK，我试试
> 
> 试zipformer 或者conv-emformer.

CPU模式下一切正常，zipformer和lstm，lstm效果差一些，zipformer和conv-emformer效果比较好
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18194268/221327310-8189b0dc-77ef-4223-bf33-5510dd1159f3.png">

**Comment by spianmo** [comment]
我陆续会把所有模型都试一遍

**Comment by spianmo** [comment]
观察到一个现象，同样的模型在安卓手机和低性能的安卓AR眼镜上推理的结果不一样。我能理解识别速度上可能有差异，但是为啥推理结果会有差异？安卓眼镜上明显效果差一些，具体表现在识别出来的结果都是同音字，字音准确字形不准确，是decoder相关的性能问题吗？此外小模型在低性能安卓眼镜上的识别准确度明显好于大一些的模型（这句话好像有点多余🥲）

**Comment by spianmo** [comment]
也可能是不同设备麦克风的原因，穿戴式安卓设备往往麦克风会有不算准确的降噪算法改变了声音的细节，具体我可以后续写个demo对比一下对一段提前准备好的wav在不同设备上的准确度效果。就是从模型本身角度讲，设备计算性能会影响推理准确度吗？非推理速度

**Comment by csukuangfj** [comment]
设备的计算性能，会影响推理速度。如果推理速度慢了， RTF > 1 的话，就会丢音频数据，从而影响准确度。

所以，在低端设备上，第一件事，就是使用 executable `sherpa-ncnn` 去测一下 RTF.

注：`sherpa-ncnn` 跑完后，会自动输出  RTF 。RTF < 1 , 才可以正常使用。你也可以测试不同解码方法和不同线程数量的 RTF.

**Comment by spianmo** [comment]
sherpa-ncnn项目可以开个GitHub Sponsors赞助通道🤠

**Comment by spianmo** [comment]
> 设备的计算性能，会影响推理速度。如果推理速度慢了， RTF > 1 的话，就会丢音频数据，从而影响准确度。
> 
> 
> 
> 所以，在低端设备上，第一件事，就是使用 executable `sherpa-ncnn` 去测一下 RTF.
> 
> 
> 
> 注：`sherpa-ncnn` 跑完后，会自动输出  RTF 。RTF < 1 , 才可以正常使用。你也可以测试不同解码方法和不同线程数量的 RTF.

感谢解答

**Comment by csukuangfj** [comment]
正对低端设备，我们特别提供了一个文档
https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/small-models.html

这个文档里面的模型，都是小模型，适合在低端设备上跑。
