### ISSUE TITLE
请问如何限制一句话的最高长度

### ISSUE THREAD

**Issue by busisiji** [k2-fsa/sherpa-ncnn#126]
比如一句话多余10个字就清空recognizer.text

**Comment by csukuangfj** [comment]
Recognizer 有个方法，叫做Reset()，你可以调用它。

**Comment by busisiji** [comment]
![image](https://user-images.githubusercontent.com/92677771/221069621-0df679cf-50a4-4bdb-ac16-83d4de9f3e6c.png)

**Comment by csukuangfj** [comment]
你用python? 

那就用

recognizer.recognizer.reset()

**Comment by busisiji** [comment]
好的，非常感谢
