### ISSUE TITLE
能否做成一个标准库？

### ISSUE THREAD

**Issue by Baiyuetribe** [k2-fsa/sherpa-ncnn#128]
在执行了`cmake build .`命令后，得到了shrpa-ncnn的相关静态库，但是头文件没有，这样就不能在其他项目里直接调用了。
<img width="937" alt="image" src="https://user-images.githubusercontent.com/43716063/221127045-601cb16b-50fd-4046-b932-cf53e0c00f22.png">

一般的C程序，编译后都会提供静态lib文件和include目录，方便快速集成到其他项目里。所以期望build后生成`sherpa-ncnnConfing.cmake`文件或补充一下install构建后的`include`目录

**Comment by csukuangfj** [comment]
> 在执行了cmake build .命令后，得到了shrpa-ncnn的相关静态库，但是头文件没有，这样就不能在其他项目里直接调用了。

你使用
```
cmake -DCMAKE_INSTALL_PREFIX=./install ..
make -j
make install
```

你可以在当前目录下，找到一个 `./install` 目录。里面有你想要的东西。

**Comment by csukuangfj** [comment]
> 得到了shrpa-ncnn的相关静态库

如果你想要动态库，请使用
```bash
cmake \
  -DBUILD_SHARED_LIBS=ON \
  -DCMAKE_INSTALL_PREFIX=./install \
..
```

这两个选项，都是标准的 CMake 参数.

**Comment by Baiyuetribe** [comment]
成功。-DCMAKE_INSTALL_PREFIX=./install 建议在cmake里设置为默认，方便其他人

**Comment by kkroid** [comment]
实测，windows添加了-DCMAKE_INSTALL_PREFIX./install也没有生成install文件夹

**Comment by csukuangfj** [comment]
> 实测，windows添加了-DCMAKE_INSTALL_PREFIX./install也没有生成install文件夹

请贴你使用的完整命令，及运行的 log.

**Comment by csukuangfj** [comment]
> 
实测，windows添加了-DCMAKE_INSTALL_PREFIX./install也没有生成install文件夹

正确的命令是
```
-DCMAKE_INSTALL_PREFIX=./install
```

你漏掉了 `=`.

**Comment by kkroid** [comment]
cmake -T v143,host=x64 -A x64 -D BUILD_SHARED_LIBS=ON -D CMAKE_INSTALL_PREFIX=E:\github\sherpa-ncnn\build-win\install -D CMAKE_BUILD_TYPE=Release ..
 cmake --build . --config Release -j

**Comment by csukuangfj** [comment]
你没有运行 install 呀。

你要跑
```
cmake --build . --config Release --target install
```

你漏掉了 
```
--target install
```

你要告诉 cmake, 你想 install, 它才会 install. 

cmake 很笨的。

**Comment by kkroid** [comment]
好的，多谢，实际上不是cmake很笨，是我很笨:(
