### ISSUE TITLE
how to deal with 8K

### ISSUE THREAD

**Issue by shenzaimin** [k2-fsa/sherpa-ncnn#144]

**Comment by shenzaimin** [comment]
我在处理8k音频的时候，将其重采样到了16k，但是在使用python api 识别该16k音频文件时报错，信息如下：
 self.recognizer.decode()
IndexError: deque::_M_range_check: __n (which is 18446744073709551341)>= this->size() (which is 10000)

请问这是什么原因呢？

**Comment by csukuangfj** [comment]
你可以贴完整的命令么？

支持  8k 或者其他采样率。

你可以用这个文件测试, 把里面的 filename 换成你自己的  8k wave 就可以了
https://github.com/k2-fsa/sherpa-ncnn/blob/master/python-api-examples/decode-file.py

**Comment by shenzaimin** [comment]
您好，我看到recognizer.py里仍然是默认16k，在assert时会报错：
# all of our current models are using 16 kHz audio samples
        self.sample_rate = 16000
...

    def accept_waveform(self, sample_rate: float, waveform: np.array):
        """Decode audio samples.

        Args:
          sample_rate:
            Sample rate of the input audio samples. It should be 16000.
          waveform:
            A 1-D float32 array containing audio samples in the
            range ``[-1, 1]``.
        """
        **_assert sample_rate == self.sample_rate_**, (sample_rate, self.sample_rate)
        self.recognizer.accept_waveform(sample_rate, waveform)
        self.recognizer.decode()

**Comment by csukuangfj** [comment]
> 您好，我看到recognizer.py里仍然是默认16k，在assert时会报错：

你用的是最新的 代码么？

---

最新的代码，长下面这样
https://github.com/k2-fsa/sherpa-ncnn/blob/0de3fb1c8031f3366cbe5de83b2668eb4166f8d8/sherpa-ncnn/python/sherpa_ncnn/recognizer.py#L205-L218

**Comment by shenzaimin** [comment]
明白了，我的版本是1.5.2，我更新一下，感谢您的解答～

**Comment by csukuangfj** [comment]
> 明白了，我的版本是1.5.2，我更新一下，感谢您的解答～

请使用最新的  master 分支的代码。

你可以使用
https://k2-fsa.github.io/sherpa/ncnn/python/index.html#installation
文档中的 method2, 3, 或者 4进行安装.

**Comment by shenzaimin** [comment]
get it～ 谢谢～
