### ISSUE TITLE
build with vulkan in linux

### ISSUE THREAD

**Issue by xiangxyq** [k2-fsa/sherpa-ncnn#145]
Hi,
when use build in linux with these command:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/18209169/223443065-660bc0e5-72f1-4564-9191-15fa2441d582.png">
seems not use vulkan, log is : Don't Use GPU. has_gpu: 0, config.use_vulkan_compute: 0

and when build like this: 

cmake -DNCNN_VULKAN=ON ../

`-- Downloading ncnn from https://github.com/csukuangfj/ncnn/archive/refs/tags/sherpa-0.9.tar.gz
-- ncnn is downloaded to /workspace/dopamine-data/chenjiang/gitlab/k2/xyyq_sherpa-ncnn/build/_deps/ncnn-src
-- ncnn's binary dir is /workspace/dopamine-data/chenjiang/gitlab/k2/xyyq_sherpa-ncnn/build/_deps/ncnn-build
-- CMAKE_INSTALL_PREFIX = /usr/local
-- NCNN_VERSION_STRING = 1.0.20230307
CMake Warning at build/_deps/ncnn-src/CMakeLists.txt:442 (message):
  The compiler does not support avx vnni extension.  NCNN_AVXVNNI will be
  OFF.

CMake Warning at build/_deps/ncnn-src/CMakeLists.txt:460 (message):
  The compiler does not support avx512 bf16 extension.  NCNN_AVX512BF16 will
  be OFF.

CMake Warning at build/_deps/ncnn-src/CMakeLists.txt:467 (message):
  The compiler does not support avx512 fp16 extension.  NCNN_AVX512FP16 will
  be OFF.

-- Target arch: x86 64bit
CMake Error at build/_deps/ncnn-src/CMakeLists.txt:544 (message):
  The submodules were not downloaded! Please update submodules with "git
  submodule update --init" and try again.

-- Configuring incomplete, errors occurred!
`
I just quickly fix this by clone [glslang](https://github.com/KhronosGroup/glslang) when ncnn needed(this step should automatic, not manual)

but decode result is error:
emformer：
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/18209169/223448498-031cd2dd-ba00-477b-8d5f-5f7f44547828.png">

lstm ：
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/18209169/223449331-b2897126-2790-40ca-b4bf-2e209d877860.png">

zipformer:
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/18209169/223449565-f6d53d1b-724b-461c-bcf8-719f304f429f.png">

**Comment by csukuangfj** [comment]
1. Please follow our android doc to build with vulkan.

We have detailed documentation and build script for it.

2. The vulkan support seems to be broken in our own ncnn fork.

**Comment by xiangxyq** [comment]
because I am not familiar with Vulkan, does Ubuntu not support vulkan, how to use gpu in Ubuntu?

**Comment by csukuangfj** [comment]
> because I am not familiar with Vulkan, does Ubuntu not support vulkan, how to use gpu in Ubuntu?

I think it is mainly used for mobile phones.

**Comment by xiangxyq** [comment]
Thx!
