### ISSUE TITLE
how to export sherpa-ncnn in pruned_transducer_stateless5

### ISSUE THREAD

**Issue by Yymax-max** [k2-fsa/sherpa-ncnn#146]
how to export sherpa-ncnn in pruned_transducer_stateless5.Have some example？

**Comment by csukuangfj** [comment]
> how to export sherpa-ncnn in pruned_transducer_stateless5.Have some example？

Please have a look at our documentation:
https://k2-fsa.github.io/icefall/model-export/export-ncnn.html

We only support the following models for exporting to ncnn
- LSTM transducer
- ConvEmformer
- Streaming zipformer

**Comment by Yymax-max** [comment]
> > how to export sherpa-ncnn in pruned_transducer_stateless5.Have some example？
> 
> Please have a look at our documentation: https://k2-fsa.github.io/icefall/model-export/export-ncnn.html
> 
> We only support the following models for exporting to ncnn
> 
> * LSTM transducer
> * ConvEmformer
> * Streaming zipformer

Is there any plan to support？

**Comment by csukuangfj** [comment]
> > > how to export sherpa-ncnn in pruned_transducer_stateless5.Have some example？
> > 
> > 
> > Please have a look at our documentation: https://k2-fsa.github.io/icefall/model-export/export-ncnn.html
> > We only support the following models for exporting to ncnn
> > 
> > * LSTM transducer
> > * ConvEmformer
> > * Streaming zipformer
> 
> Is there any plan to support？

Sorry, it is not in the plan.

Streaming zipformer is our current best-performing model and we already support it.

**Comment by Yymax-max** [comment]
> > > > how to export sherpa-ncnn in pruned_transducer_stateless5.Have some example？
> > > 
> > > 
> > > Please have a look at our documentation: https://k2-fsa.github.io/icefall/model-export/export-ncnn.html
> > > We only support the following models for exporting to ncnn
> > > 
> > > * LSTM transducer
> > > * ConvEmformer
> > > * Streaming zipformer
> > 
> > 
> > Is there any plan to support？
> 
> Sorry, it is not in the plan.
> 
> Streaming zipformer is our current best-performing model and we already support it.

ok，thank

**Comment by csukuangfj** [comment]
Please see
https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#pruned_transducer_stateless8-zipformer--multidataset

It is also zipformer.


----

By the way, the RESULTS.md from each recipe keeps the results of each experiment.
You can find the results from there.

**Comment by Yymax-max** [comment]
> 

thank

**Comment by joazoa** [comment]
@csukuangfj  can the new zipformer (offline version --causal 0 ) be exported with ncnn ? If so, how  and where can i find some code to do offline decoding with the ncnn version ?

**Comment by csukuangfj** [comment]
> the new zipformer (offline version --causal 0 ) be exported with ncnn 

No.

sherpa-ncnn supports only streaming models.

**Comment by csukuangfj** [comment]
> @csukuangfj can the new zipformer (offline version --causal 0 ) be exported with ncnn ? If so, how and where can i find some code to do offline decoding with the ncnn version ?

All supported models are listed in the documentation.
https://k2-fsa.github.io/icefall/model-export/export-ncnn.html

If a model is not listed here, then it is not supported.

**Comment by joazoa** [comment]
Thank you for the lightning fast answer!

I suppose the "zipformer" in the document only refers to the older version (transducer_stateless7_streaming ) and not to the new zipformer with causal=1 ) ?

**Comment by csukuangfj** [comment]
> I suppose the "zipformer" in the documentation only refers to the older version 

Yes, you are right. The new version `./zipformer` has not been supported yet, but it is in the plan.

**Comment by csukuangfj** [comment]
We will first support sherpa-onnx. There is an on-going issue about it. https://github.com/k2-fsa/icefall/issues/1094
After it is supported, we will start to support sherpa-ncnn.


Could you try sherpa-onnx first once it is supported?

**Comment by joazoa** [comment]
@csukuangfj  Now that the Onnx export is done, what is needed for the ncnn export for the zipformer2 ? How can we (try to) help ?

Could we use https://github.com/Tencent/ncnn/blob/master/tools/onnx/onnx2ncnn.cpp ?
