### ISSUE TITLE
Failed to load ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.param

### ISSUE THREAD

**Issue by sun-rabbit** [k2-fsa/sherpa-ncnn#162]
在jetson nano板子上进行实时语音识别时候
sunxt@roybox-desktop:~/kaldi/sherpa-ncnn/build-arm-linux-gnueabihf/install$ ./bin/sherpa-ncnn-alsa \
>   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/tokens.txt \
>   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.param \
>   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.bin \
>   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/decoder_jit_trace-pnnx.ncnn.param \
>   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/decoder_jit_trace-pnnx.ncnn.bin \
>   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/joiner_jit_trace-pnnx.ncnn.int8.param \
>   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/joiner_jit_trace-pnnx.ncnn.int8.bin \
>   "hw:1,0"
DecoderConfig(method="greedy_search", num_active_paths=4)
fopen ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.param failed
Failed to load ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.param
Current sample rate: 16000
Recording started!
Use recording device: hw:1,0
Segmentation fault (core dumped)
缺少文件，但是我下载模型时候已经下载了，这个是需要自己编译的吗

**Comment by csukuangfj** [comment]
> 在jetson nano板子上进行实时语音识别时候
> 
> sunxt@roybox-desktop:~/kaldi/sherpa-ncnn/build-arm-linux-gnueabihf/install$ ./bin/sherpa-ncnn-alsa \
> 
> >   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/tokens.txt \
> 
> >   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.param \
> 
> >   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.bin \
> 
> >   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/decoder_jit_trace-pnnx.ncnn.param \
> 
> >   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/decoder_jit_trace-pnnx.ncnn.bin \
> 
> >   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/joiner_jit_trace-pnnx.ncnn.int8.param \
> 
> >   ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/joiner_jit_trace-pnnx.ncnn.int8.bin \
> 
> >   "hw:1,0"
> 
> DecoderConfig(method="greedy_search", num_active_paths=4)
> 
> fopen ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.param failed
> 
> Failed to load ./sherpa-ncnn-conv-emformer-transducer-small-2023-01-09/encoder_jit_trace-pnnx.ncnn.int8.param
> 
> Current sample rate: 16000
> 
> Recording started!
> 
> Use recording device: hw:1,0
> 
> Segmentation fault (core dumped)
> 
> 缺少文件，但是我下载模型时候已经下载了，这个是需要自己编译的吗

请检查文件大小是否和文档中的匹配。确保你使用了git lfs 下载模型文件。

**Comment by sun-rabbit** [comment]
> 

total 29M
-rw-r--r-- 1 sunxt sudo 314K Mar 21 11:12 decoder_jit_trace-pnnx.ncnn.bin
-rw-r--r-- 1 sunxt sudo  436 Mar 21 11:10 decoder_jit_trace-pnnx.ncnn.param
-rwxr-xr-x 1 sunxt sudo  389 Mar 21 11:10 decode.sh
-rw-r--r-- 1 sunxt sudo  16M Mar 21 11:13 encoder_jit_trace-pnnx.ncnn.bin
-rw-r--r-- 1 sunxt sudo  12M Mar 21 11:13 encoder_jit_trace-pnnx.ncnn.int8.bin
-rwxr-xr-x 1 sunxt sudo 104K Mar 21 11:10 encoder_jit_trace-pnnx.ncnn.int8.param
-rw-r--r-- 1 sunxt sudo 105K Mar 21 11:10 encoder_jit_trace-pnnx.ncnn.param
-rw-r--r-- 1 sunxt sudo  454 Mar 21 11:10 export-ncnn.sh
-rw-r--r-- 1 sunxt sudo 607K Mar 21 11:12 joiner_jit_trace-pnnx.ncnn.bin
-rw-r--r-- 1 sunxt sudo 311K Mar 21 11:12 joiner_jit_trace-pnnx.ncnn.int8.bin
-rw-r--r-- 1 sunxt sudo  495 Mar 21 11:10 joiner_jit_trace-pnnx.ncnn.int8.param
-rw-r--r-- 1 sunxt sudo  487 Mar 21 11:10 joiner_jit_trace-pnnx.ncnn.param
-rw-r--r-- 1 sunxt sudo  435 Mar 21 11:10 README.md
drwxr-xr-x 2 sunxt sudo 4.0K Mar 21 11:10 test_wavs
-rw-r--r-- 1 sunxt sudo 5.0K Mar 21 11:10 tokens.txt
-rw-r--r-- 1 sunxt sudo  494 Mar 21 11:10 train.sh
-rw-r--r-- 1 sunxt sudo  378 Mar 21 11:10 wave-filenames-04.txt
你好，我通过ls -lh 显示文件大小存在的

**Comment by csukuangfj** [comment]
那可以编译个debug 版本，然后在命令前面加上

gdb --args 

看看是哪里出现的问题。

**Comment by csukuangfj** [comment]
你是不是文件路径写错了？

**Comment by sun-rabbit** [comment]
> 那可以编译个debug 版本，然后在命令前面加上
> 
> gdb --args
> 
> 看看是哪里出现的问题。

更改成绝对路径好使了 哈哈哈哈
