### ISSUE TITLE
语音交互咨询

### ISSUE THREAD

**Issue by sun-rabbit** [k2-fsa/sherpa-ncnn#168]
我尝试了用k2进行语音识别，但是语音交互这方面不是很懂，如果我在jetson nano板子上（arm）进行语音交互（asr,nlp,tts），我怎么把识别出来的文字传给nlp呢，我咨询了chatgpt，以及谷歌搜索，都没有很好的建议，大佬可以给出一些指点或者学习方向吗

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-ncnn/blob/3602f15556da250b47466ebe0d63a085d6eca322/sherpa-ncnn/csrc/sherpa-ncnn-alsa.cc#L163-L165

你可以在这个 if 语句里面，把 text 送给其他应用。

**Comment by sun-rabbit** [comment]
> https://github.com/k2-fsa/sherpa-ncnn/blob/3602f15556da250b47466ebe0d63a085d6eca322/sherpa-ncnn/csrc/sherpa-ncnn-alsa.cc#L163-L165
> 
> 你可以在这个 if 语句里面，把 text 送给其他应用。
这个是需要把k2识别出来的文本保存到一个指定的文件夹里面吧

**Comment by csukuangfj** [comment]
具体怎么使用这个识别结果，看你的需求。

不建议你保存在一个文本里面。

你可以考虑不同应用之间，如何通信，传递数据。

**Comment by sun-rabbit** [comment]
> 具体怎么使用这个识别结果，看你的需求。
> 
> 不建议你保存在一个文本里面。
> 
> 你可以考虑不同应用之间，如何通信，传递数据。

这个应该怎么应用呢，我目前做到的就是能够用mic进行实时识别，但是我想发出我的指令，就比如说，“请向前走”， if (!text.empty()) { 
   ++segment_index; 
 } 这个怎么使用的有教程嘛

**Comment by csukuangfj** [comment]
```bash
 if (!text.empty()) { 
   if (text == "请向前走") {
    // 执行你要的命令
  }
 } 
```
