### ISSUE TITLE
[Feature Request] a Proactive Mandarin Syllable Recognition Engine

### ISSUE THREAD

**Issue by diyism** [k2-fsa/sherpa-ncnn#177]
I've compiled the sherpa-ncnn android app with the model "sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23",
the target apk is amazing, only 30MB, it can rather accurately and quickly recognize my chinese words.

My feature request is to use Sherpa-ncnn only as a general syllable recognition engine, and push the speed to the extreme,
so that I can use it as both a hotword detection engine and a long sentence recognition engine.
I can use it as a general hotword detection engine(without fixed pretrained hotwords) to quickly response my users(see the "亭子"(ting2 zhi3), "停止"(ting2 zhi3) in the 2nd attached image),
meanwhile if I need understand the meaning of a long voice of the user,
I can send the output syllable/pinyin sequence to the LLM (eg.ChatGPT-4),
then the ChatGPT-4 can response me the most right chinese characters of the best semantic analysis in the world.

Typically every mandarin syllable cost the same fixed 0.3 seconds, most mandarin syllables contains only "a consonant + a vowel" or "a vowel", so I think that the extreme fast recognition can finish before the user finish pronouncing a mandarin syllable.(see the 1st attached image of phoneme spectrogram)
there're some projects which target is  about the syllable/pinyin segmentation, for example:
whisper-timestamped: https://github.com/linto-ai/whisper-timestamped
and a very concise tool aeneas: https://github.com/readbeyond/aeneas

I'm dreaming such a Proactive Syllable Recognition Engine that can achieve the precision of a mechanical keyboard.

My naive idea is that maybe I can modify the training procedure of "sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23" to build this syllable/pinyin recognition model first (maybe we need to modify the sherpa-ncnn engine itself as well),
There are only 1300 mandarin syllables with tone in total.
any hint?

ref: Possible to use for real-time / streaming tasks https://github.com/openai/whisper/discussions/2#discussioncomment-5499999
ref: Transcribe to IPA (International Phonetic Alphabet)  https://github.com/openai/whisper/discussions/318#discussioncomment-5499879

![a](https://user-images.githubusercontent.com/1744399/230778035-754865b5-5a7c-427e-800e-301a3c68b6ca.png)

![Screenshot 2023-04-09 at 22-57-21 Photo - Google Photos](https://user-images.githubusercontent.com/1744399/230780178-f2727ed2-a49a-4d76-9579-9e5e0a820e70.png)

**Comment by diyism** [comment]
ref:
https://huggingface.co/marcoyang/sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23/tree/main
https://github.com/k2-fsa/icefall/pull/906

@marcoyang1998 @csukuangfj  Any guide to train the sherpa-ncnn-streaming-zipformer-zh, if I want to train a model to recognize only 1300 pinyin?

**Comment by pkufool** [comment]
Did you ever train a streaming zipformer on char-based? If so, I only thing you need to do is to modified stage 15 in prepare.sh (https://github.com/k2-fsa/icefall/blob/6434c8eadc0d4326e1db69824cf0e40dc9a71c8a/egs/wenetspeech/ASR/prepare.sh#L191),  and change `-t char` in this line https://github.com/k2-fsa/icefall/blob/6434c8eadc0d4326e1db69824cf0e40dc9a71c8a/egs/wenetspeech/ASR/prepare.sh#L206 to `-t pinyin`.

**Comment by diyism** [comment]
> 

Cool, I'll give a try.

**Comment by diyism** [comment]
@pkufool 
I guess the "sherpa-ncnn-streaming-zipformer-zh" model was trained with "pruned_transducer_stateless7_streaming"(https://k2-fsa.github.io/icefall/recipes/Streaming-ASR/librispeech/zipformer_transducer.html)

It seems that only the "egs/librispeech/ASR/" and "egs/csj/ASR/" has "pruned_transducer_stateless7_streaming",
while the "egs/wenetspeech/ASR/" has no "pruned_transducer_stateless7_streaming",
but "egs/librispeech/ASR/prepare.sh" has no "Stage 15: Prepare char based lang", any hint?

**Comment by diyism** [comment]
@danpovey , is there any idea to build a Proactive Mandarin Syllable Recognition Engine?
It can finish recognizing a mandarin syllable before the user finish pronouncing a mandarin syllable (a chinese character),
because a mandarin syllable only contains "a vowel" or "a consonant + a vowel" without any tail consonant(for example, the 'sk' in the word "desk"),
typically the mandarin syllable length is the fixed 0.3 seconds,
a  Proactive Mandarin Syllable Recognition Engine can recognize it without the over-length tail of a syllable.

**Comment by danpovey** [comment]
sorry, closing this issue as i think the idea isn't very specific or achievable.  speech recognition relies on context, including future context, because speech is not as unambiguous as you think.  we alreay have pretty good latency.

**Comment by diyism** [comment]
It's sad that you think Proactive Mandarin Syllable Recognition is not achievable, but I believe that this requirement is really important.

Vocabulary and sentences are constantly evolving, with their numbers becoming increasingly abundant. However, there are only forever 1300 fixed syllables or pinyin in Chinese.

Therefore, I think the analysis of vocabulary and sentences should be left to large language models (such as ChatGPT-4 or Claude instant), while the ASR engines should focus more on the recognition of syllables.

For example, if next year we have a new internet buzzword to recognize: "盖火"(gai4  huo3), the current model "sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23" will recognized as "概括"(gai4 kuo4), it's far wrong, although the second single syllable "huo3" is very easy to recognize, we can send this prompt to Claude instant:

"First, translate into the standard Chinese Pinyin, with the final number in each section representing the four tones of Mandarin Chinese. Then, translate into Chinese characters, with the corresponding tone matching the given Pinyin: gai4 huo3."

it can give me the right chinese characters (but currently GPT-4 or GPT-3.5 can't):
![Screenshot 2023-04-20 at 14-11-10 Claude-instant - Poe](https://user-images.githubusercontent.com/1744399/233274017-2b05e733-380d-429a-951a-fd693aa921b7.png)

**Comment by marcoyang1998** [comment]
> It seems that only the "egs/librispeech/ASR/" and "egs/csj/ASR/" has "pruned_transducer_stateless7_streaming",
while the "egs/wenetspeech/ASR/" has no "pruned_transducer_stateless7_streaming",
but "egs/librispeech/ASR/prepare.sh" has no "Stage 15: Prepare char based lang", any hint?

Sorry, I didn't open a PR for that. But if you need it, I can open one.

As a workaround, if you only want to generate Chinese Pinyin output, you can modify the output units of the model. For example, the original output units (in tokens.txt) are:
```bash
语 0
音 1
识 2
别 3
```

To only output Chinese Pinyin, you can modify it to the following:
```bash
yu3 0
yin1 1
shi2 2
bie2 3
```

This should partially solve your problem. Then you can use some language models to convert them into Chinese characters.

**Comment by diyism** [comment]
> 

Great, could you do me a favor to support "egs/wenetspeech/ASR/" + "pruned_transducer_stateless7_streaming"?
Then I'll try to train it with the pure pinyin  tokens.txt.

**Comment by diyism** [comment]
@marcoyang1998 Any updates? I can only rely on you. I've tried the YonaVox training, the recognition accuracy for single mandarin syllable  can reach 88%, but I failed to import my trained model into the android phone: https://github.com/yonatankarimish/YonaVox/issues/2

**Comment by marcoyang1998** [comment]
Sorry, I was busy with other projects and didn't find time to do it. Will make the PR this week.

**Comment by diyism** [comment]
Any updates?
Or does anyone know of any other open source solutions for speech recognition at the syllable level?

**Comment by diyism** [comment]
![Screenshot 2023-07-10 at 11-01-08 Malcolm Ke Win(已fo者邀fo我必允fo) on Twitter](https://github.com/k2-fsa/sherpa-ncnn/assets/1744399/c801a6e1-6616-49b4-bbd2-af8a5d1cadbd)
@danpovey, I have updated the feature request to "Syllable-level Voice Recognition for 1300 Mandarin pinyins". I request to reopen this issue. 

Nowadays, application development based on voice interaction + LLM (such as ChatGPT) has become very popular, but they have not been able to solve the most basic problem of "accurate interaction". 

For example, using ChatGPT to ask children questions like "Please choose the correct Chinese word corresponding to the pinyin 'gài huǒ' and read it out: 1.盖括 2.各火 3.盖火 4.给火", it is difficult for the speech recognition engine to distinguish which one of the four options the child is reading. Moreover, if one of the four options can be accurately recognized, there is no need to click the "Tap to stop recording" button at the bottom of the screenshot, which can protect children's eyesight without their having to stare at the screen.

I believe that "Syllable-level Voice Recognition" is the only solution to this problem of accurate interaction.

**Comment by pkufool** [comment]
@diyism  OK, will add the syllable-level model, it is not hard to implement this base on our recipe, we already provide the script to convert Chinese characters to pinyin. We thought you have fixed this yet.

**Comment by diyism** [comment]
Great, if we can achieve it, we'll have a 1300-key keyboard, and the users can use it very conveniently.
![F0rLfV1aQAEEsdt](https://github.com/k2-fsa/sherpa-ncnn/assets/1744399/45365600-6ff1-4fea-9d02-714875b87ce0)

**Comment by diyism** [comment]
Nowadays, both -claude.ai and -chat.openai.com gpt3.5 are very good at analyzation and understanding of long pinyin sentences:
![Screenshot 2023-07-16 at 10-10-31 Claude](https://github.com/k2-fsa/sherpa-ncnn/assets/1744399/e8221271-fa0e-4c8d-8df3-dea9502e21b9)
![Screenshot 2023-07-16 at 10-10-01 ChatGPT](https://github.com/k2-fsa/sherpa-ncnn/assets/1744399/65c7c7aa-25be-45cc-aa8c-19d04e469998)


While the sherpa-ncnn can't (I want to eat the garden made with fish meat.)
![a](https://github.com/k2-fsa/sherpa-ncnn/assets/1744399/eddd5b89-923d-498a-a882-0f18aa386dad)

So I insist that ASR should focus more on Syllable-level Voice Recognition,
and leave long sentence semantic analysis to large language models(claude2, gpt3.5 etc),
and leave hot word detection to straightforward pinyin comparison.

@danpovey

**Comment by diyism** [comment]
![Screenshot 2023-07-19 at 09-27-42 Chat And Battle With Open LLMs - a Hugging Face Space by lmsys](https://github.com/k2-fsa/sherpa-ncnn/assets/1744399/bba88b1e-aff8-44f3-a73f-b4be160a268c)

What a pity that the ability of llama2 13b to understand Pinyin sentences is still not up to par,
and it can't be used as a post-processing component for voice recognition like -claude.ai or -chat.openai.com gpt3.5.
Otherwise, we indie hackers could have already replaced Apple's Siri with open-source models. 
But, I can feel it, the llama2 13b is already very close,
so I strongly desire that sherpa-ncnn can become a prerequisite component for we indie hackers to create realtime interaction apps(both long sentence understanding and dynamic hot word detection).
