### ISSUE TITLE
是否支持长段的录音文件识别？

### ISSUE THREAD

**Issue by DelogoTeam** [k2-fsa/sherpa-ncnn#180]
是否支持几分钟长度的录音文件识别

**Comment by csukuangfj** [comment]
几分钟，还是支持的。

如果你使用流式识别，那么就对长度没有限制。如果是非流式识别，最大的长度，取决于你电脑的内存有多大。

**Comment by DelogoTeam** [comment]
请问有对识别结果添加标点符号的规划，或者解决方案吗

**Comment by csukuangfj** [comment]
> 请问有对识别结果添加标点符号的规划，或者解决方案吗

目前没有规划。

你可以外接加标点符号的模型，这个应该是 NLP 的范畴？

**Comment by csukuangfj** [comment]
> 请问有对识别结果添加标点符号的规划，或者解决方案吗

@DelogoTeam 

sherpa-onnx 支持加标点了。请看如下文档
https://k2-fsa.github.io/sherpa/onnx/punctuation/index.html
