### ISSUE TITLE
执行 build-android-arm64-v8a.sh 编译出错

### ISSUE THREAD

**Issue by norkmGitHub** [k2-fsa/sherpa-ncnn#185]
根据 https://k2-fsa.github.io/sherpa/ncnn/android/build-sherpa-ncnn.html 里面的流程，在执行 build-android-x86-64.sh 这个步骤出现了以下错误：

$ ./build-android-arm64-v8a.sh
+ dir=build-android-arm64-v8a
+ export ANDROID_NDK=D:/Android/Sdk/ndk/22.1.7171670
+ ANDROID_NDK=D:/Android/Sdk/ndk/22.1.7171670
+ mkdir -p build-android-arm64-v8a
+ cd build-android-arm64-v8a
+ '[' -z D:/Android/Sdk/ndk/22.1.7171670 ']'
+ '[' '!' -d D:/Android/Sdk/ndk/22.1.7171670 ']'
+ echo 'ANDROID_NDK: D:/Android/Sdk/ndk/22.1.7171670'
ANDROID_NDK: D:/Android/Sdk/ndk/22.1.7171670
+ sleep 1
+ cmake -DCMAKE_TOOLCHAIN_FILE=D:/Android/Sdk/ndk/22.1.7171670/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DSHERPA_NCNN_ENABLE_PORTAUDIO=OFF -DSHERPA_NCNN_ENABLE_BINARY=OFF -DSHERPA_NCNN_ENABLE_TEST=OFF -DSHERPA_NCNN_ENABLE_C_API=OFF -DSHERPA_NCNN_ENABLE_GENERATE_INT8_SCALE_TABLE=OFF -DCMAKE_INSTALL_PREFIX=./install -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 ..
-- Building for: Visual Studio 17 2022
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    D:/vscode/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    MSBuild version 17.4.1+9a89d02ff for .NET Framework
    生成启动时间为 2023/4/19 15:41:58。
    节点 1 上的项目“D:\chromeDownload\sherpa-ncnn-master (1)\sherpa2\sherpa-ncnn\build-android-arm64-v8a\CMakeFiles\3.26.3\VCTargetsPath.vcxproj”(默认目标)。
    D:\vscode\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\chromeDownload\sherpa-ncnn-master (1)\sherpa2\sherpa-ncnn\build-android-arm64-v8a\CMakeFiles\3.26.3\VCTargetsPath.vcxproj]
    已完成生成项目“D:\chromeDownload\sherpa-ncnn-master (1)\sherpa2\sherpa-ncnn\build-android-arm64-v8a\CMakeFiles\3.26.3\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “D:\chromeDownload\sherpa-ncnn-master (1)\sherpa2\sherpa-ncnn\build-android-arm64-v8a\CMakeFiles\3.26.3\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (_CheckForInvalidConfigurationAndPlatform 目标) ->
      D:\vscode\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\chromeDownload\sherpa-ncnn-master (1)\sherpa2\sherpa-ncnn\build-android-arm64-v8a\CMakeFiles\3.26.3\VCTargetsPath.vcxproj]

        0 个警告
        1 个错误

    已用时间 00:00:00.10

  Exit code: 1

-- Configuring incomplete, errors occurred!

**Comment by csukuangfj** [comment]
这个脚本，不适合在 windows 上跑，它需要在 linux 或者 macos 上跑。

如果你没有 linux 或者 macos， 请下载我们编译好的 动态库，然后你就可以跳过 运行`build-android-x86-64.sh` 这一步

下载链接，可以在 https://github.com/k2-fsa/sherpa-ncnn/releases 找到。

比如下面这个，是目前最新的
[sherpa-ncnn-v1.8.1-pre-compiled-android-libs.tar.bz2](https://github.com/k2-fsa/sherpa-ncnn/releases/download/v1.8.1/sherpa-ncnn-v1.8.1-pre-compiled-android-libs.tar.bz2)

**Comment by norkmGitHub** [comment]
非常感谢，可以运行了。我还想问一下 这 10个 模型文件有描述吗，我看项目中好像用到 6 个模型就可以运行，删除4个多余的文件应该不会影响使用吧。

**Comment by norkmGitHub** [comment]
非常感谢，可以运行了。我还想问一下 这 10个 模型文件有描述吗，我看项目中好像用到 6 个模型就可以运行。

```
{
            val modelDir = "sherpa-ncnn-conv-emformer-transducer-2022-12-06"
            return ModelConfig(
                encoderParam = "$modelDir/encoder_jit_trace-pnnx.ncnn.int8.param",
                encoderBin = "$modelDir/encoder_jit_trace-pnnx.ncnn.int8.bin",
                decoderParam = "$modelDir/decoder_jit_trace-pnnx.ncnn.param",
                decoderBin = "$modelDir/decoder_jit_trace-pnnx.ncnn.bin",
                joinerParam = "$modelDir/joiner_jit_trace-pnnx.ncnn.int8.param",
                joinerBin = "$modelDir/joiner_jit_trace-pnnx.ncnn.int8.bin",
                tokens = "$modelDir/tokens.txt",
                numThreads = 4,
                useGPU = useGPU,
            )

        }
```

我想删除另外4个多余的文件应该不会影响使用吧。

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/index.html
上面链接包含了所有提供的模型，代码里面，应该没有写全。你可以选择一个适合你自己的。


> 非常感谢，可以运行了。我还想问一下 这 10个 模型文件有描述吗，我看项目中好像用到 6 个模型就可以运行。

你想删掉哪 4 个？可以描述详细点吗

**Comment by norkmGitHub** [comment]
encoder_jit_trace-pnnx.ncnn.bin
encoder_jit_trace-pnnx.ncnn.param
joiner_jit_trace-pnnx.ncnn.bin
joiner_jit_trace-pnnx.ncnn.param 想删这四个，我看安卓demo项目里没有用到。
