### ISSUE TITLE
what is input data format?

### ISSUE THREAD

**Issue by DickyQi** [k2-fsa/sherpa-ncnn#19]
I need know what kind of input audio format is, I mean input into ncnn network? such is waveform data with single channel 16k float32, or stft/fft audio data?

**Comment by csukuangfj** [comment]
You can find the format in
https://github.com/k2-fsa/sherpa-ncnn/blob/8c2b44e29856d5a8764a18054682cb3b20edc573/sherpa-ncnn/csrc/wave-reader.cc#L102-L105

It supports 16-bit, 16k Hz, mono WAVE (i.e., single channel). 

When it is read to memory, you have to normalize it to the range [-1, 1].

**Comment by DickyQi** [comment]
@csukuangfj Thanks!!! Because audio algorithm using frequency domain data generally, so I asked. wave-reader is simply get waveform data from file,  and then send data into knf::OnlineFbank. What my real question was data format into ncnn inforence network? I checked kaldi_native_fbank-src code, it seems compute waveform data features into rfft(stft) format, which is  frequency domain data. Am I right?

**Comment by csukuangfj** [comment]
> it seems compute waveform data features into rfft(stft) format, which is frequency domain data. Am I right?

Yes.

We are using fbank features (i.e., filter bank), which is one of the most.most.most. frequently used features for speech recognition.

The following link 
https://wiki.aalto.fi/display/ITSP/Cepstrum+and+MFCC
may be helpful for you.

**Comment by DickyQi** [comment]
I understood now. You are using fbank as audio feature extract, including fft. low pass filter, mcl filter. Then send filterd data into ncnn. Thanks for you anwser, it is realy helpful.
