### ISSUE TITLE
How to run sherpa-ncnn on macbook pro 

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/sherpa-ncnn#193]
How to run sherpa-ncnn on macbook pro

**Comment by PPGGG** [comment]
Yeah i have successfully ran it. But how can i export a library to make it work inside a mac app ?

**Comment by csukuangfj** [comment]
```bash
git clone https://github.com/k2-fsa/sherpa-ncnn
cd sherpa-ncnn
mkdir build
cd build
cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=ON \
  -DCMAKE_INSTALL_PREFIX=./install \
  ..

make -j6 install
```
and you will find the required header files and shared libraries inside `./install`.

Please remove your `./build` directory before you re-try.

**Comment by PPGGG** [comment]
Thanks a lot. Really appreciated.
