### ISSUE TITLE
weird recognized result from windows

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/sherpa-ncnn#196]
I have successfully built sherpa-ncnn on windows 32 bit system. However, i found the result looked weird. I think the encoding format may have something to modify. The model i used is the one named `sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23`.

The results is below 
`瀵规垜鍋氫簡浠嬬粛閭ｄ箞鎴戞兂璇寸殑鏄ぇ瀹跺鏋滃鎴戠殑鐮旂┒鎰熷叴瓒?`

**Comment by csukuangfj** [comment]
Please read our doc. 

![Screenshot 2023-05-06 at 15 30 50](https://user-images.githubusercontent.com/5284924/236609983-debfc83b-764a-461b-947f-7ef1b4113a7b.png)


https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#decode-a-single-wave-file

**Comment by csukuangfj** [comment]
By the way, if you are using a desktop or a laptop, I suggest that you use a larger model, which has a better recognition accuracy than small models.

**Comment by PPGGG** [comment]
@csukuangfj Yeah sure. Thanks for your kind consideration for us.
