### ISSUE TITLE
iOS demo 内存太高

### ISSUE THREAD

**Issue by DelogoTeam** [k2-fsa/sherpa-ncnn#197]
在iOS上运行demo的时候，内存高达200多M，请问有什么方法可以优化一下吗

**Comment by csukuangfj** [comment]
你使用哪个模型呢？

**Comment by csukuangfj** [comment]
请用 num_threads=1, decoding_method="greedy_search" 试试.

**Comment by DelogoTeam** [comment]
decoder_jit_trace-pnnx.ncnn.bin

**Comment by csukuangfj** [comment]
Please give us more information.

**Comment by DelogoTeam** [comment]
decoder_jit_trace-pnnx.ncnn.bin
decoder_jit_trace-pnnx.ncnn.param
encoder_jit_trace-pnnx.ncnn.bin
encoder_jit_trace-pnnx.ncnn.param
oiner_jit_trace-pnnx.ncnn.bin
joiner_jit_trace-pnnx.ncnn.param
我用的是上面这些，然后我将num_threads改为了1，内存还是有200多M

**Comment by csukuangfj** [comment]
请给多一点信息。sherpa-ncnn 里面，所有的模型，都是用这几个文件。
比如说，你使用哪个链接下载的模型，模型的文件夹名字是什么？

你要得到我们的帮助的话，你提供的信息，越详细越好。

**Comment by DelogoTeam** [comment]
我是从这个链接下载的模型[https://huggingface.co/marcoyang/sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23
cd sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23](url)
我重新下载了并运行了一次，这次内存是70M左右，回复了正常。我想可能是我之前的步骤有些不对吧。
感谢你的帮助

**Comment by csukuangfj** [comment]
这是个很小的模型，准确率，没有大一点的模型好。

**Comment by DelogoTeam** [comment]
我用了这个模型：
[https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-en-2023-02-13](url)
在测试的时候内存直接飙升到了300多M

**Comment by csukuangfj** [comment]
模型文件就占了100多MB.

你期望的内存占用量是多少呢？

LSTM 模型，内存占用量是最少的，但它的速度最慢。（如果速度符合你的要求，你用 lstm 也可以).

**Comment by DelogoTeam** [comment]
我希望能够在100M左右是比较好的，我换成LSTM试试看

**Comment by csukuangfj** [comment]
> 我希望能够在100M左右是比较好的，我换成LSTM试试看

你更看重准确率，还是内存占用量？
