### ISSUE TITLE
new ncnn code inference result not right

### ISSUE THREAD

**Issue by DickyQi** [k2-fsa/sherpa-ncnn#20]
I try to using newest ncnn code to replace _dep folder ncnn code, which is only missing lstm2 layer. Compile OK, but run inference got wrong result. Is your ncnn source code do some special modifications?

**Comment by csukuangfj** [comment]
You can have a look at the commit history of the master branch of
https://github.com/csukuangfj/ncnn

---

I will find some time to support the official ncnn.

**Comment by csukuangfj** [comment]
Should be fixed by #207
