### ISSUE TITLE
Android out of memory crash with GPU

### ISSUE THREAD

**Issue by hristorv** [k2-fsa/sherpa-ncnn#203]
I have built and tested the demo app on Android running on the CPU and everything works fine. But when I try to run it on the GPU I have an out-of-memory crash. But if I use the int8 model files there is no crash and the app works. This is what I am getting from the Android logcat:
```
Use GPU
<sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
<gsl_memory_alloc_pure:2297>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
vkAllocateMemory failed -2
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x108 in tid 19589 (Thread-4), pid 19252 (fsa.sherpa.ncnn)
```

**Comment by csukuangfj** [comment]
Which version of sherpa-ncnn and which model are you using?

Can you try sherpa-ncnn <= v1.4.1

**Comment by hristorv** [comment]
I am using the latest version and model - sherpa-ncnn-streaming-zipformer-20M-2023-02-17
And there is no crash with model int8 - sherpa-ncnn-conv-emformer-transducer-2022-12-06

**Comment by csukuangfj** [comment]
> sherpa-ncnn-streaming-zipformer-20M-2023-02-17

there is no int8 model for the above model. Do you generate int8 models by yourself?

**Comment by hristorv** [comment]
The int8 model is - sherpa-ncnn-conv-emformer-transducer-2022-12-06

**Comment by csukuangfj** [comment]
Can you try sherpa-ncnn <= v1.4.1

**Comment by csukuangfj** [comment]
Or you can try tomorrow the latest master of sherpa-ncnn. I am fixing it.

**Comment by hristorv** [comment]
Tried with tag v1.4.1 and I still have the crash

**Comment by hristorv** [comment]
I've tested the new version 2.0 with the new model and I can confirm that it works.
