### ISSUE TITLE
[help and question] Can I create a dictionary that lets text results show my own pharses first? for instance, a specific term in science

### ISSUE THREAD

**Issue by XinLi0111** [k2-fsa/sherpa-ncnn#217]
I am a student working on taxonomy, and I want to use this great tool to help me translate my voice into text in real time. It does not work very well in special terms in my field. Of course, it does not affect the advantages of Sherpa-ncnn.
I wonder whether there is a not very complicated way to define a vocabulary of special terms and use them as first results.

**Comment by pkufool** [comment]
I think this is similar to the context biasing, we indeed have a PR on sherpa-onnx (https://github.com/k2-fsa/sherpa-onnx/pull/145), it has not been merged yet, we are waiting for some benchmarks. I am hoping we will get some solid results as soon as possible, then I will implement it on sherpa-ncnn.

It would be great if you have some test wavs, you can find us by joining us from the qr code below:

![](https://user-images.githubusercontent.com/5284924/180991981-77f822cc-e228-43b2-b679-a0108f8fa5fb.png)

**Comment by XinLi0111** [comment]
It's just a idea, I am not start prepare my own wav yet.

**Comment by m-aliabbas** [comment]
I am also waiting for it, because I have to use it for VoIP calling. And it have some abusive word but its not including it.

**Comment by pkufool** [comment]
@m-aliabbas  I think sherpa-ncnn already supports that.

**Comment by XinLi0111** [comment]
Thanks for all and their effort on this useful function!
