### ISSUE TITLE
Android Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/sherpa-ncnn#218]
When i tried to run the android app for a long time, it suddenly quit given the error shown on the logcat below:

```
com.k2fsa.sherpa.ncnn                A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 26018 (HeapTaskDaemon), pid 26000 (fsa.sherpa.ncnn)
com.k2fsa.sherpa.ncnn                E  endActivityTransaction: margin state not match
```

**Comment by csukuangfj** [comment]
Are there any more detailed logs?

**Comment by PPGGG** [comment]
Quite strange. It just came out of these two error. I am not sure what happened. I will try to observe the performance further. Thanks.
