### ISSUE TITLE
[help] "Failed to read" wav file 

### ISSUE THREAD

**Issue by jwanga** [k2-fsa/sherpa-ncnn#220]
Are there constraints on wav file format that can be used during inference?  I generated an uncompressed 32-bit 8000 hz mono wave with Adobe Audition and I'm receiving the following error:

`Failed to read ./sherpa-ncnn-2022-09-05/test_wavs/test.wav`

**Comment by csukuangfj** [comment]
Could you provide a wave of 16 kHz, single channel, 16-bit per sample?

**Comment by jwanga** [comment]
Nevermind, my encoder settings were incorrect, everything works fine now. Thank you @csukuangfj!
