### ISSUE TITLE
Unsqueeze batch dim 0 is not support yet

### ISSUE THREAD

**Issue by wbjnpu** [k2-fsa/sherpa-ncnn#221]
大佬使用pnnx导出时是否遇到过这个问题，请问是怎么解决的，谢谢。我在转其他模型遇到的问题

**Comment by csukuangfj** [comment]
这个是warning , 不是error

**Comment by wbjnpu** [comment]
> 这个是warning , 不是error 

那这个对转出的模型不会有影响么？另外torch.flip也报warning，推理也会出错到这个位置，我看pnnx源码里面已经支持了啊

**Comment by csukuangfj** [comment]
你可以去ncnn里面问

**Comment by csukuangfj** [comment]
> 那这个对转出的模型不会有影响么

分享一下我们转模型的经验： 
(1) 转模型的时候，是 layer-by-layer 的转
(2) 转完一个 layer, 需要比较一下 ncnn 和 pytorch 的输出，在给定同样的输入时，是否一致
(3) 如果不一致，需要进入到这个 pytorch layer 里面, 看看是哪一行导致的。（你可以提前使用 return 语句，找到出问题的那一个语句)


---

转模型是个体力活（不是技术活），需要你很有耐心.
