### ISSUE TITLE
IOS demo cpu is much higher than Android

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/sherpa-ncnn#224]
I would like to ask the reason why the CPU performance in the IOS demo is much higher than the Android demo. They use the same model.

<img width="1646" alt="Screenshot 2023-06-14 at 14 51 41" src="https://github.com/k2-fsa/sherpa-ncnn/assets/11624203/e6ab4924-e810-43f5-b72d-dd7f8ff93798">

**Comment by csukuangfj** [comment]
But the CPUs are different, right?

Apple's CPUs are perhaps more powerful.

**Comment by PPGGG** [comment]
I notice that in the `func initRecorder()`, it wraps the recorder initialization code with the audio processing function, which is quite different from the Android implementation.

In Android implementation, it separates the recorder initialization and audio processing into two functions, which are `initMicrophone()` and `processSamples()`. I am not sure why the ios implementation didn't follow the same implementation as the Android.

**Comment by csukuangfj** [comment]
ios and android have different APIs and different programming models.

**Comment by PPGGG** [comment]
I see. I would like to explore any ways to limit the CPU usage.

**Comment by csukuangfj** [comment]
> I see. I would like to explore any ways to limit the CPU usage. For example, in Android, the CPU usage is kind of 8%. However, in IOS, the CPU usage could be up to 20%.

Do you use the same decoding method and the same num_threads for android and iOS?

**Comment by PPGGG** [comment]
Yes. They both use the same model, same num_threads, same decoding method with the other same configuration.

**Comment by PPGGG** [comment]
Can we change `pcmFormatFloat32` to `pcmFormatInt16` in `outputFormat` ?

**Comment by PPGGG** [comment]
I have tried to convert `pcmFormatFloat32 ` to `pcmFormatInt16 `. It seems the CPU performance remained the same.

**Comment by PPGGG** [comment]
I found that maybe the problem is the `opennmp`. Can we turn it off ? @csukuangfj

**Comment by csukuangfj** [comment]
Yes, we can.

Please change
https://github.com/k2-fsa/sherpa-ncnn/blob/f593f335d663458b0bb62d5ef6e9f728006c31bc/cmake/ncnn.cmake#L60
to
```cmake
 set(NCNN_BUILD_TESTS OFF CACHE BOOL "" FORCE) 

 set(NCNN_OPENMP OFF CACHE BOOL "" FORCE) 
```

and then remove your build directory and re-build from scratch.

---

Remember to remove your build directory before you retry. Otherwise, it won't work.

**Comment by PPGGG** [comment]
Do i need to change the `openmp` related content inside the `build-ios.sh` file ?

**Comment by csukuangfj** [comment]
> Do i need to change the `openmp` related content inside the `build-ios.sh` file ?

No, you don't need to do that.

**Comment by csukuangfj** [comment]
If https://github.com/k2-fsa/sherpa-ncnn/issues/224#issuecomment-1592446433 works, then you can remove openmp related stuff in `build-ios.sh` to reduce lib size.

**Comment by PPGGG** [comment]
> > Do i need to change the `openmp` related content inside the `build-ios.sh` file ?
> 
> No, you don't need to do that.

Okay. I am now trying to do that.

**Comment by PPGGG** [comment]
It seems that even i get rid of the `openmp`, the CPU usage is still very high.

**Comment by PPGGG** [comment]
> I would like to ask the reason why the CPU performance in the IOS demo is much higher than the Android demo. They use the same model.
> 
> <img alt="Screenshot 2023-06-14 at 14 51 41" width="1646" src="https://user-images.githubusercontent.com/11624203/245701415-e6ab4924-e810-43f5-b72d-dd7f8ff93798.png">

I would like to ask why there are so many nested process named `ncnn::NetPrivate::forward_layer` in ios ? @csukuangfj

**Comment by csukuangfj** [comment]
@PPGGG 
Those are not processes. They are call stacks.

**Comment by PPGGG** [comment]
Oh i see.
