### ISSUE TITLE
sherpa-ncnn例程报错：Failed to read hw:3,0

### ISSUE THREAD

**Issue by lozenyin** [k2-fsa/sherpa-ncnn#229]
本人在运行【./build/bin/sherpa-ncnn】例程是出现了Failed to read hw:3,0报错，运行指令及报错如下
`
root@fuxivision:~/app/locke/sherpa-ncnn# ./build/bin/sherpa-ncnn \
> model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/tokens.txt \
> model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/encoder_jit_trace-pnnx.ncnn.param \
> model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/encoder_jit_trace-pnnx.ncnn.bin \
> model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/decoder_jit_trace-pnnx.ncnn.param \
> model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/decoder_jit_trace-pnnx.ncnn.bin \
> model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/joiner_jit_trace-pnnx.ncnn.param \
> model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/joiner_jit_trace-pnnx.ncnn.bin \
> hw:3,0 \
> 2 \
> greedy_search
Don't Use GPU. has_gpu: 0, config.use_vulkan_compute: 1
RecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80), model_config=ModelConfig(encoder_param="model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/encoder_jit_trace-pnnx.ncnn.param", encoder_bin="model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/encoder_jit_trace-pnnx.ncnn.bin", decoder_param="model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/decoder_jit_trace-pnnx.ncnn.param", decoder_bin="model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/decoder_jit_trace-pnnx.ncnn.bin", joiner_param="model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/joiner_jit_trace-pnnx.ncnn.param", joiner_bin="model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/joiner_jit_trace-pnnx.ncnn.bin", tokens="model/sherpa-ncnn-streaming-zipformer-small-bilingual-zh-en-2023-02-16/tokens.txt", encoder num_threads=2, decoder num_threads=2, joiner num_threads=2), decoder_config=DecoderConfig(method="greedy_search", num_active_paths=4), endpoint_config=EndpointConfig(rule1=EndpointRule(must_contain_nonsilence=False, min_trailing_silence=2.4, min_utterance_length=0), rule2=EndpointRule(must_contain_nonsilence=True, min_trailing_silence=1.4, min_utterance_length=0), rule3=EndpointRule(must_contain_nonsilence=False, min_trailing_silence=0, min_utterance_length=20)), enable_endpoint=False)
Failed to read hw:3,0

`
音频设备验证过可以识别与录音
`
card 3: Y360 [Star Y360], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`
该命令能够成功获取录音文件
`
arecord -D hw:3,0 -d 10 -f cd -t wav -c 1 test.wav
`
请问一下这个错误要如何处理解决？

**Comment by csukuangfj** [comment]
> 请问一下这个错误要如何处理解决？

请把
```
./build/bin/sherpa-ncnn 
```
替换成
```
./build/bin/sherpa-ncnn-alsa
```

出错的原因是，你使用了错误的二进制程序。

如果你找不到  build/bin/sherpa-ncnn-alsa, 请参考
https://k2-fsa.github.io/sherpa/ncnn/faq.html#no-default-input-device-found

**Comment by lozenyin** [comment]
哦哦，成功运行，谢谢~！
