### ISSUE TITLE
在编译安装Python接口的时候是否可与修改一下make的参数为-j2?

### ISSUE THREAD

**Issue by lozenyin** [k2-fsa/sherpa-ncnn#230]
`
root@orangepizero2:~/sherpa-ncnn# python3 setup.py install
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing sherpa_ncnn.egg-info/PKG-INFO
writing dependency_links to sherpa_ncnn.egg-info/dependency_links.txt
writing requirements to sherpa_ncnn.egg-info/requires.txt
writing top-level names to sherpa_ncnn.egg-info/top_level.txt
reading manifest file 'sherpa_ncnn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'pyproject.toml'
adding license file 'LICENSE'
writing manifest file 'sherpa_ncnn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
copying sherpa-ncnn/python/sherpa_ncnn/__init__.py -> build/lib.linux-aarch64-3.10/sherpa_ncnn
running build_ext
Setting PYTHON_EXECUTABLE to /usr/bin/python3
for fast compilation, run:
export SHERPA_NCNN_MAKE_ARGS="-j"; python setup.py install
Setting make_args to "-j4"
build command is:

                cd build/temp.linux-aarch64-3.10

                cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_INSTALL_PREFIX=/root/sherpa-ncnn/build/lib.linux-aarch64-3.10/sherpa_ncnn  -DBUILD_SHARED_LIBS=ON  -DSHERPA_NCNN_ENABLE_PYTHON=ON  -DSHERPA_NCNN_ENABLE_PORTAUDIO=OFF  /root/sherpa-ncnn

                make -j4 install/strip

-- CMAKE_EXPORT_COMPILE_COMMANDS: ON
-- BUILD_SHARED_LIBS ON
-- SHERPA_NCNN_ENABLE_PYTHON ON
-- SHERPA_NCNN_ENABLE_PORTAUDIO OFF
-- SHERPA_NCNN_ENABLE_JNI OFF
-- SHERPA_NCNN_ENABLE_BINARY ON
-- SHERPA_NCNN_ENABLE_TEST OFF
-- SHERPA_NCNN_ENABLE_C_API ON
-- SHERPA_NCNN_ENABLE_GENERATE_INT8_SCALE_TABLE ON
-- SHERPA_NCNN_ENABLE_FFMPEG_EXAMPLES OFF
-- CMAKE_BUILD_TYPE: Release
-- Downloading kaldi-native-fbank from https://github.com/csukuangfj/kaldi-native-fbank/archive/refs/tags/v1.14.tar.gz
-- kaldi-native-fbank is downloaded to /root/sherpa-ncnn/build/temp.linux-aarch64-3.10/_deps/kaldi_native_fbank-src
-- kaldi-native-fbank's binary dir is /root/sherpa-ncnn/build/temp.linux-aarch64-3.10/_deps/kaldi_native_fbank-build
-- CMAKE_BUILD_TYPE: Release
-- BUILD_SHARED_LIBS: ON
-- KALDI_NATIVE_FBANK_BUILD_TESTS: OFF
-- KALDI_NATIVE_FBANK_BUILD_PYTHON: OFF
-- KALDI_NATIVE_FBANK_ENABLE_CHECK: OFF
-- KALDI_NATIVE_FBANK_ENABLE_CHECK: OFF
-- CMAKE_CXX_FLAGS:
-- CMAKE_INSTALL_PREFIX: /root/sherpa-ncnn/build/lib.linux-aarch64-3.10/sherpa_ncnn
-- Disable building Python
-- Downloading ncnn from https://github.com/csukuangfj/ncnn/archive/refs/tags/sherpa-1.1.tar.gz
-- ncnn is downloaded to /root/sherpa-ncnn/build/temp.linux-aarch64-3.10/_deps/ncnn-src
-- ncnn's binary dir is /root/sherpa-ncnn/build/temp.linux-aarch64-3.10/_deps/ncnn-build
-- CMAKE_INSTALL_PREFIX = /root/sherpa-ncnn/build/lib.linux-aarch64-3.10/sherpa_ncnn
-- NCNN_VERSION_STRING = 1.0.20230621
-- Target arch: arm 64bit
-- Downloading pybind11 from https://github.com/pybind/pybind11/archive/refs/tags/v2.10.2.tar.gz
-- pybind11 is downloaded to /root/sherpa-ncnn/build/temp.linux-aarch64-3.10/_deps/pybind11-src
-- pybind11 v2.10.2
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sherpa-ncnn/build/temp.linux-aarch64-3.10

`
上述是执行了`python3 setup.py install `后的输出，可以看到make的参数为-J4，在我当前部署的设备中运行得比较吃力，是否可以调成-j2?要在哪里修改？

**Comment by csukuangfj** [comment]
请使用
```bash
export SHERPA_NCNN_MAKE_ARGS="-j2"
python3 setup.py install
```

你只需要设置 `SHERPA_NCNN_MAKE_ARGS` 这个环境变量就好了.

---

此外，如果是在 ARM 设备上 运行，我推荐你用下面的安装方法
https://k2-fsa.github.io/sherpa/ncnn/python/index.html#method-4-for-developers-and-embedded-boards

**Comment by csukuangfj** [comment]
@lozenyin  请问上面的回答，解决了你的问题没有？

**Comment by lozenyin** [comment]
已经解决了，感谢感谢！
