### ISSUE TITLE
How to implement hotwords using sherpa-ncnn?

### ISSUE THREAD

**Issue by peterdogdog** [k2-fsa/sherpa-ncnn#259]
How to implement hotwords using sherpa-ncnn? Thanks.

**Comment by csukuangfj** [comment]
There is an on-going PR
https://github.com/k2-fsa/sherpa-ncnn/pull/257

Please wait before it is merged.

**Comment by peterdogdog** [comment]
Okay. May I ask how long it will take? Thanks. Can't wait to try this.

**Comment by HalFTeen** [comment]
> Okay. May I ask how long it will take? Thanks. Can't wait to try this.

done

**Comment by csukuangfj** [comment]
Merged.

Please see
https://github.com/k2-fsa/sherpa-ncnn/pull/260#issuecomment-1700485184
for an example
