### ISSUE TITLE
android studio 部署问题求解答

### ISSUE THREAD

**Issue by fawnjwka** [k2-fsa/sherpa-ncnn#266]
经过对您的代码了解，我对此本地离线语音识别能力非常感兴趣，但是有关于构建 sherpa-ncnn（C++ 代码）处，由于我用的是win系统但是也想要通过android studio成功部署该代码，该节的构建脚本只适用于 macOS 和 Linux。请问能否通过win进行构建，是否有详细教程，求学

**Comment by csukuangfj** [comment]
请去
https://github.com/k2-fsa/sherpa-ncnn/releases

下载我们编译好的 libs.

比如
https://github.com/k2-fsa/sherpa-ncnn/releases/download/v2.0.2/sherpa-ncnn-v2.0.2-pre-compiled-android-libs.tar.bz2

或者你下载一个我们编译好的 apk, 然后解压，然后找到你需要的 .so 文件，然后就可以按照文档继续了。

**Comment by fawnjwka** [comment]
感谢您的回复，由于我在其中只找到了编译好的apk未能找到相应编译好的库给您添麻烦了，再次感谢您的奉献，我将持续关注您的奉献

**Comment by csukuangfj** [comment]
<img width="1228" alt="Screenshot 2023-09-05 at 16 03 42" src="https://github.com/k2-fsa/sherpa-ncnn/assets/5284924/5d8a0560-7e96-4b34-be23-ec367dc31e80">


这个是解压 apk 后得到的，你想要的 .so, apk 里都有。

**Comment by csukuangfj** [comment]
请问这个issue 解决了吗？

**Comment by csukuangfj** [comment]
请问这个issue 解决了吗？

**Comment by fawnjwka** [comment]
您好这个问题得到了解决，我目前已经在对接模型了，感谢您的答复
