### ISSUE TITLE
ffmpeg编译不了，缺少libcodec

### ISSUE THREAD

**Issue by timfengzi** [k2-fsa/sherpa-ncnn#272]
在windows环境下，开启ffmpeg配置编译不了，缺少libcodec

**Comment by csukuangfj** [comment]
你是ffmpeg5吗？请贴具体的log?

**Comment by timfengzi** [comment]
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/8926448/30632926-045c-4c81-8f3c-373ac1580145)

**Comment by csukuangfj** [comment]
问了两个问题。请回答下你是否是 ffmpeg5

**Comment by timfengzi** [comment]
是这个版本git-2020-03-01-1281399

**Comment by timfengzi** [comment]
用ffmpeg6也是不行，Mac用6是可以的

**Comment by timfengzi** [comment]
sherpa-ncnn-ffmpeg是不是不兼容windows，这个没编译出来，sherpa-ncnn是可以的

**Comment by timfengzi** [comment]
错误 | C2065 | “SIGUSR1”: 未声明的标识符 | C:\msys64\sherpa\sherpa-ncnn\out\build\x64-Debug\sherpa-ncnn | C:\msys64\sherpa\sherpa-ncnn\ffmpeg-examples\sherpa-ncnn-ffmpeg.cc | 612 |

**Comment by csukuangfj** [comment]
> sherpa-ncnn-ffmpeg是不是不兼容windows，这个没编译出来，sherpa-ncnn是可以的

这个只在 linux 和 macos 试过，没有在 windows上试过。应该是有办法支持的。

**Comment by timfengzi** [comment]
可以了，修改了一些文件，但不知道对不对。

sherp-ncnn-ffmpeg.cc头文件去掉了unistd.h，加上了#include <io.h>
#include <process.h>

加上了static int32_t SIGUSR1 = 0x10;

sherp-ncnn-ffmpeg cmake文件去掉了pkgconfig相关，加上了ffmpeg编译出来的链接库或把ffmpeg编译出来的链接库复制到windows下也行

**Comment by csukuangfj** [comment]
> 可以了，修改了一些文件，但不知道对不对。
> 
> sherp-ncnn-ffmpeg.cc头文件去掉了unistd.h，加上了#include <io.h> #include <process.h>
> 
> 加上了static int32_t SIGUSR1 = 0x10;
> 
> sherp-ncnn-ffmpeg cmake文件去掉了pkgconfig相关，加上了ffmpeg编译出来的链接库或把ffmpeg编译出来的链接库复制到windows下也行

方便提个 pull-request 吗？

**Comment by timfengzi** [comment]
windows7，windows10都可以，windows11不行
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/8926448/62472bee-acfd-4e8d-ae93-21224a076cf9)

**Comment by csukuangfj** [comment]
这个是模型文件不完整。你检查下模型文件大小就知道了。应该是没用 git lfs pull

**Comment by timfengzi** [comment]
可以了，确实是模型文件不完整。请问有群吗，我发现一段长语音，在sherpa-ncnn准确率很低，在腾讯云的语音识别准确率很高，能不能自己训练模型？

**Comment by csukuangfj** [comment]
有群的, qq 和 微信群。

入群方式在我们的文档里，请阅读
https://k2-fsa.github.io/sherpa/social-groups.html

**Comment by timfengzi** [comment]
已经申请加群，非常好，准确率很高，但是有些同音的还是有错，比如学情分析变成了学琴分析，说课变成了说客等同音情况。
