### ISSUE TITLE
无法访问huggingface.co

### ISSUE THREAD

**Issue by Roboticshwx** [k2-fsa/sherpa-ncnn#275]
在下载语言模型的时候无法访问huggingface.co

局部代理也无法访问，改为全局代理之后可以访问

**Comment by overtherain** [comment]
https://www.modelscope.cn/pkufool/sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23.git
这个模型不管下载几遍, 文件大小都不对

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-ncnn/releases/tag/models

这里可以下载

<img width="1033" alt="Screenshot 2023-11-22 at 18 11 52" src="https://github.com/k2-fsa/sherpa-ncnn/assets/5284924/841b60e6-bdb6-4f4b-8461-89dfa192f889">

**Comment by pkufool** [comment]
> https://www.modelscope.cn/pkufool/sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23.git 这个模型不管下载几遍, 文件大小都不对 ![image](https://user-images.githubusercontent.com/3395745/284854638-30348935-51b7-4425-8309-8deedc5de25d.png)

你装 git-lfs 了吗？ modelscope 也是用 lfs 来管理的，和 huggingface 一样。
