### ISSUE TITLE
How to add punctuation after detecting endpoint?

### ISSUE THREAD

**Issue by OswaldoBornemann** [k2-fsa/sherpa-ncnn#279]
How to add punctuation after detecting endpoint?

**Comment by csukuangfj** [comment]
Currently, it is not supported.

You can add a punctuation model at the end to process the output.

**Comment by OswaldoBornemann** [comment]
I see.

**Comment by csukuangfj** [comment]
@OswaldoBornemann 

We have supported adding punctuations in sherpa-onnx.
Please see
https://k2-fsa.github.io/sherpa/onnx/punctuation/index.html
