### ISSUE TITLE
pa_stable_v190700_20210406.tgz

### ISSUE THREAD

**Issue by magicse** [k2-fsa/sherpa-ncnn#286]
-- verifying file...
       file='Z:/1111111/Whisper/sherpa-ncnn/Build/_deps/portaudio-subbuild/portaudio-populate-prefix/src/pa_stable_v190700_20210406.tgz'
-- SHA256 hash of
    Z:/1111111/Whisper/sherpa-ncnn/Build/_deps/portaudio-subbuild/portaudio-populate-prefix/src/pa_stable_v190700_20210406.tgz
  does not match expected value
    expected: '47efbf42c77c19a05d22e627d42873e991ec0c1357219c0d74ce6a2948cb2def'
      actual: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
-- File already exists but hash mismatch. Removing...

**Comment by csukuangfj** [comment]
please delete the build directory and retry,

**Comment by csukuangfj** [comment]
have you fixed it?

**Comment by magicse** [comment]
Yes i fixed this. thank You
Also I get some issues with pa_stable.  I use mingw64 on windows.
Like - undefined reference to `max' and  - undefined reference to `min'
Looks like min and max are only defined by default in visual studio but not in MINGW
I think it need replace it with fmax and fmin... for MINGW 
Or  just adding a super simple definition at the top of the file 
#define min(X,Y) ((X) < (Y) ? (X) : (Y))
#define max(X,Y) ((X) > (Y) ? (X) : (Y))

**Comment by csukuangfj** [comment]
we have never tried MingW. Please use VS in Windows.

**Comment by magicse** [comment]
Sorry but i love MINGW and all my projects with ncnn under MINGW. 
In any way it will work ))). I resolve any issues ))
