### ISSUE TITLE
很棒的repo，感谢你们的工作，请问有计划添加多说话人时的话者分离功能吗？

### ISSUE THREAD

**Issue by Tony-xubiao** [k2-fsa/sherpa-ncnn#288]
Speaker diarization

**Comment by csukuangfj** [comment]
感谢关注。

目前还没有。

**Comment by csukuangfj** [comment]
我们有说话人识别的功能了。欢迎尝试

https://k2-fsa.github.io/sherpa/onnx/speaker-identification/apk.html

**Comment by csukuangfj** [comment]
@Tony-xubiao 

http://github.com/k2-fsa/sherpa-onnx
已经支持了 speaker diarization
