### ISSUE TITLE
集成Android上语音识别，无法识别成功。

### ISSUE THREAD

**Issue by Tom-xdf** [k2-fsa/sherpa-ncnn#290]
中文识别有时候能够识别成功，英语识别十次有九次不能识别成功，且识别出来的英语字母都是大写。

**Comment by csukuangfj** [comment]
1. 你用的是哪个模型？
2. 是你自己说的英语么？有没有尝试过播放英语音频？
3. 大写这个问题，你自己转成小写就好了

**Comment by Tom-xdf** [comment]
1、用的英文模型，但是识别中文说的很慢能识别部分。
2、我自己说英语偶尔能识别到，也是不能识别完全，识别度不高，最后我使用英语音频来进行识别，偶尔识别到，但是识别错误。

**Comment by csukuangfj** [comment]
用具体说你用的是哪个模型。

**Comment by Tom-xdf** [comment]
![Uploading image.png…]()
这一个

**Comment by Tom-xdf** [comment]
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/85798556/4a59a5eb-3109-46de-bf43-b036e9a12042)

**Comment by csukuangfj** [comment]
你手机是什么配置呢？

https://github.com/k2-fsa/sherpa-ncnn/releases/download/v2.1.4/sherpa-ncnn-2.1.4-cpu-arm64-v8a-bilingual-en-zh.apk
你用这个 apk 试过么？

**Comment by Tom-xdf** [comment]
手机是Pixel2，也用国产手机试过。
用你发的APK进行语音识别，国产能识别到语音，识别度也挺高

**Comment by Tom-xdf** [comment]
那个手机cpu配置确实不行，但是我更换手机在你发的apk上面，识别英语就很灵敏，我把模型copy出来，识别语音几乎全部转换为中文，用英语音频去识别也有时候出现识别不成功的情况。

**Comment by csukuangfj** [comment]
用同样的手机测试我们的 apk 和你自己编译的 apk 吗

**Comment by Tom-xdf** [comment]
是的

**Comment by Tom-xdf** [comment]
同样的手机配置，测试自己编译的apk和你们的apk效果 不同

**Comment by csukuangfj** [comment]
你用的是哪个模型呢？还有，你是如何编译的，做了什么修改

**Comment by Tom-xdf** [comment]
已解决，更换了一个你们只识别英语的模型
