### ISSUE TITLE
语音识别结果不是很好，有推荐的中文模型吗

### ISSUE THREAD

**Issue by summerHearts** [k2-fsa/sherpa-ncnn#291]
目前使用的模型是 marcoyang/sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23 (Chinese)[](https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#marcoyang-sherpa-ncnn-streaming-zipformer-zh-14m-2023-02-23-chinese) 
能否给出建议，使用哪个模型，不胜感激

**Comment by csukuangfj** [comment]
你用的是一个 14M 的模型，参数量非常小，优势是速度极快。缺点是准确率没有大一点的模型高.

推荐你用
https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#csukuangfj-sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13-bilingual-chinese-english

**Comment by summerHearts** [comment]
我看到这里有一个模型，这个能用吗，看样子是最新的，https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html#sherpa-onnx-pre-trained-models
<img width="703" alt="image" src="https://github.com/k2-fsa/sherpa-ncnn/assets/10678821/8b3177c1-dd81-423a-b2ae-418e04d5abe8">

**Comment by csukuangfj** [comment]
> 我看到这里有一个模型，这个能用吗，看样子是最新的，https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html#sherpa-onnx-pre-trained-models <img alt="image" width="703" src="https://private-user-images.githubusercontent.com/10678821/292357993-8b3177c1-dd81-423a-b2ae-418e04d5abe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTI1NzQsIm5iZiI6MTcwMzIxMjI3NCwicGF0aCI6Ii8xMDY3ODgyMS8yOTIzNTc5OTMtOGIzMTc3YzEtZGQ4MS00MjNhLWIyYWUtNDE4ZTA0ZDVhYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAyMzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZjZjM2Y0YzY0NDI2YTljYTQzZGZhZjM5NGZlNzBlZmY2MmE1ZmI3NzY3MGM2MzRiZGRlYjQ5ODc3MTA4MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DJgBXa2iuLT4a3a0Qmd8YKUTGpu1Kg5TkNGQ3Bl2HPw">

这个是给 onnx 用的，不是给 ncnn 用的。如果你用 sherpa-onnx, 那么， 是可以的。

**Comment by summerHearts** [comment]
sherpa-onnx

> > 我看到这里有一个模型，这个能用吗，看样子是最新的，https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html#sherpa-onnx-pre-trained-models <img alt="image" width="703" src="https://private-user-images.githubusercontent.com/10678821/292357993-8b3177c1-dd81-423a-b2ae-418e04d5abe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTI1NzQsIm5iZiI6MTcwMzIxMjI3NCwicGF0aCI6Ii8xMDY3ODgyMS8yOTIzNTc5OTMtOGIzMTc3YzEtZGQ4MS00MjNhLWIyYWUtNDE4ZTA0ZDVhYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAyMzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZjZjM2Y0YzY0NDI2YTljYTQzZGZhZjM5NGZlNzBlZmY2MmE1ZmI3NzY3MGM2MzRiZGRlYjQ5ODc3MTA4MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DJgBXa2iuLT4a3a0Qmd8YKUTGpu1Kg5TkNGQ3Bl2HPw">
> 
> 这个是给 onnx 用的，不是给 ncnn 用的。如果你用 sherpa-onnx, 那么， 是可以的。


我理解 sherpa-onnx,支持语音到文本（speech-to-text）和文本到语音（text-to-speech）的任务，那么是否推荐使用这个，移动端上使用

**Comment by csukuangfj** [comment]
> 那么是否推荐使用这个，移动端上使用

sherpa-ncnn 和 sherpa-onnx, 我们都推荐.

**Comment by summerHearts** [comment]
从体积考虑前者120M，移动端不是很适合。那么是否建议使用 
<img width="714" alt="image" src="https://github.com/k2-fsa/sherpa-ncnn/assets/10678821/d886e693-4bb8-44a0-b6c0-36c7e360cf3e">
.int8.onnx 格式的来接入移动端。

**Comment by csukuangfj** [comment]
模型摆在这里。你自己选个合适你自己的。
