### ISSUE TITLE
在rk3568开发板arm32系统上跑官方demo，15s跑出609s正常吗，是不是哪里没有设置正确

### ISSUE THREAD

**Issue by jackwenshann** [k2-fsa/sherpa-ncnn#292]
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/90788900/200b8e95-8c8e-46ce-9ed1-c70a6df3807a)

**Comment by csukuangfj** [comment]
用的是哪个模型？请把完整的文件夹名字贴出来

**Comment by jackwenshann** [comment]
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/90788900/cba90cdc-a9f3-489f-abc9-97b90da7e66a)
用的test_wavs 05.wav文件测试的
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/90788900/cc68049b-d12e-4cf7-97e4-8fc06f7e7862)
使用的版本

**Comment by csukuangfj** [comment]
你的 cpu 是 cortex A7 还是什么其他型号？
如果是 A7，那么你现在用的这个模型太大了，你的 cpu 性能太弱，跑不起来。可以换个小模型。文档里有专门关于小模型的页面。

**Comment by jackwenshann** [comment]
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/90788900/1b3bf340-1b80-4e06-86eb-5c23e62a850d)
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/90788900/c877766f-c6fa-42e4-bcf7-d3338f6cf0ef)
![image](https://github.com/k2-fsa/sherpa-ncnn/assets/90788900/86f989dc-8198-4e82-a667-26f8d538f6c5)
rk3568性能应该够了，不知道哪里有问题我这边4核的，用htop看，执行时只有一个cpu跑满

**Comment by csukuangfj** [comment]
你才 4 个 cpu ，最多用 4 个线程。我看你用了 12，这个起反作用了。不是越大越快。相反，还会更慢

**Comment by jackwenshann** [comment]
哦哦，好的。cpu如何才能跑满呢

**Comment by csukuangfj** [comment]
你有 4 个，就用 4 个线程

**Comment by csukuangfj** [comment]
不一定保证全跑满，因为这个计算量，不需要这么多 cpu ，但能保证，4 个 cpu 都有被用上。
