### ISSUE TITLE
如何Android中实现中文语音识别

### ISSUE THREAD

**Issue by kada0720** [k2-fsa/sherpa-ncnn#298]
请问有使用Kaldi在Android中实现中文语音识别的文档吗，找了一会儿没找到清晰的使用方法。
期待得到大家的回复~

**Comment by csukuangfj** [comment]
你说的是新一代Kaldi吗？

**Comment by csukuangfj** [comment]
如果你要用新一代kaldi的话，文档在
https://k2-fsa.github.io/sherpa/ncnn/android/build-sherpa-ncnn.html

**Comment by HassanTen** [comment]
> 如果你要用新一代kaldi的话，文档在 https://k2-fsa.github.io/sherpa/ncnn/android/build-sherpa-ncnn.html

How is this step applied in detail?
Build sherpa-ncnn (C++ code)

**Comment by csukuangfj** [comment]
> > 如果你要用新一代kaldi的话，文档在 https://k2-fsa.github.io/sherpa/ncnn/android/build-sherpa-ncnn.html
> 
> How is this step applied in detail? Build sherpa-ncnn (C++ code)

We have described it in detail in the doc. Could you tell us which step you think is not clear?

**Comment by HassanTen** [comment]
> > > 如果你要用新一代kaldi的话，文档在 https://k2-fsa.github.io/sherpa/ncnn/android/build-sherpa-ncnn.html
> > 
> > 
> > How is this step applied in detail? Build sherpa-ncnn (C++ code)
> 
> We have described it in detail in the doc. Could you tell us which step you think is not clear?

I tried all the applications (open source) for at least six months and did not find anything better than this application ( sherpa-ncnn-2.1.7-cpu-arm64-v8a-en )

I posted your project to everyone on Facebook, but I did not find a solution to this proble.

it is time to build the C++ code of [sherpa-ncnn](https://github.com/k2-fsa/sherpa-ncnn).

Is there a video of this application?
