### ISSUE TITLE
windows 移植编译问题

### ISSUE THREAD

**Issue by Hynsn** [k2-fsa/sherpa-ncnn#299]
看了官网教程，build-android-arm64-v8a.sh 不支持windows + android studio+cmake编译，希望作者能支持一下，我这边移植发现#include "net.h"  // NOLINT 这个文件还需要去下载，最终没成功

**Comment by csukuangfj** [comment]
两种解决方法
1. 用我们提供好的 .so 文件。（假装是你自己编译的）
2. 使用 linux 或者 macos 去编译。

得到 .so 文件后，你就可以在 windows 上用 android studio 了.

**Comment by Hynsn** [comment]
> 两种解决方法
> 
> 1. 用我们提供好的 .so 文件。（假装是你自己编译的）
> 2. 使用 linux 或者 macos 去编译。
> 
> 得到 .so 文件后，你就可以在 windows 上用 android studio 了.

好滴，还有一个问题
```kt
class SherpaNcnn(
    var config: RecognizerConfig,
    assetManager: AssetManager? = null,
) {
    private val ptr: Long

    init {
        if (assetManager != null) {
            ptr = newFromAsset(assetManager, config)
        } else {
            ptr = newFromFile(config)
        }
    }
}
```
newFromFile() 我这边想把模型放到手机外置存储然后加载，但这个没看到具体的使用demo。看了jni源码没有发现文件读写相关的操作。

**Comment by csukuangfj** [comment]
你把文件路径放在config里，替换掉assets里的路径，把assetManager设置为null，就可以啦

**Comment by csukuangfj** [comment]
@Hynsn 
是不是解决了？

**Comment by Hynsn** [comment]
是的。目前只能这样
