### ISSUE TITLE
请问使用的是什么模型

### ISSUE THREAD

**Issue by nhjydywd** [k2-fsa/sherpa-ncnn#305]
Hello，可以科普一下使用的是什么模型吗？

ASR小白一个，我听说whisper识别准确率很高，但移动端算力最多支持whisper-base。请问whisper-base和现有移动端ASR模型相比处于什么水平呢？

**Comment by csukuangfj** [comment]
> 我听说whisper识别准确率很高

听谁说的呢？是什么语言的识别率很高呢

我们也支持 whisper, 有编译好的 apk, 请去
https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.9.10
下载.

具体的下载链接是
[sherpa-onnx-1.9.10-arm64-v8a-en-2pass-whisper-tiny.en.apk](https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.9.10/sherpa-onnx-1.9.10-arm64-v8a-en-2pass-whisper-tiny.en.apk)

(这个 apk 只支持英文识别)
