### ISSUE TITLE
请问模型是如何训练的？

### ISSUE THREAD

**Issue by SchweitzerGAO** [k2-fsa/sherpa-ncnn#312]
不好意思又来打扰，我想基于下一代Kaldi训练个其他语言的模型，故来问问发布的预训练模型有无可以参考的训练流程

**Comment by csukuangfj** [comment]
请参考
https://github.com/k2-fsa/icefall

icefall 也有自己的文档。

**Comment by SchweitzerGAO** [comment]
OK，感谢
