### ISSUE TITLE
Do we support hotwords in sherpa_ncnn?

### ISSUE THREAD

**Issue by OswaldoBornemann** [k2-fsa/sherpa-ncnn#313]
Do we support hotwords in sherpa_ncnn?

**Comment by csukuangfj** [comment]
Yes, please see
- #257 
- #260
- #285

**Comment by OswaldoBornemann** [comment]
I see. Do we need to change the decoding method to `modified_beam_search` like you did in sherpa onnx?

**Comment by csukuangfj** [comment]
Yes. sherpa-onnx and sherpa-ncnn share the same doc for hotwords.

**Comment by OswaldoBornemann** [comment]
I see. Thank you for your patience.
