### ISSUE TITLE
关于sherpa-onnx的比较

### ISSUE THREAD

**Issue by shenck0** [k2-fsa/sherpa-ncnn#316]
从模型转换难易度看，用onnx更方便，那么sherpa-ncnn的优势在于？是否是速度更快
例如，在armv8的设备上，sherpa-ncnn和sherpa-onnx在相同的tts或asr模型上，是否某一个有明显速度优势呢？

**Comment by csukuangfj** [comment]
你可以从以下几方面去比较

1. 库文件大小
2. 增加新的 operator 的容易程度，即扩展 ncnn 和 onnxruntime 的容易程度
3. 支持的 cpu 种类
4. 碰到问题时，寻求帮助的容易程度，（指 ncnn 和 onnxruntime）

---

还有，为什么只关注速度呢？速度和测试的环境有关系。你们直接测试下就知道了。

**Comment by shenck0** [comment]
你说的很全面，感谢指教！
从使用者角度，为什么更关注速度呢，因为现在模型普遍都很大，显得对库和权重文件大小不是很重要；扩展难度上因为预计不太会新增不支持的算子，主流算子已经很充分了（除非实现一些算子fusion）；从cpu种类看，两者支持范围都很广了，很大比例用户都可以选择两者之一；对量化支持程度，也回到速度问题
