### ISSUE TITLE
c++调用编译，在板子上部署

### ISSUE THREAD

**Issue by superhgq1** [k2-fsa/sherpa-ncnn#317]
我想通过c++部署，然后得到识别文本后再进行处理，目前在linux下可以编译，但是怎么在交叉环境编译，然后部署到板子上，有示例么

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/ncnn/install/aarch64-embedded-linux.html

这个 是 64-bit arm 的交叉编译的文档.

---

下面是 32-bit arm 的交叉编译文档
https://k2-fsa.github.io/sherpa/ncnn/install/arm-embedded-linux.html
