### ISSUE TITLE
x86  平台ncnn so编译不过去。

### ISSUE THREAD

**Issue by respHr** [k2-fsa/sherpa-ncnn#336]
![微信截图_20240510132337](https://github.com/k2-fsa/sherpa-ncnn/assets/106939577/babe3b75-e829-4c84-b41d-b90566446464)
![微信截图_20240510132421](https://github.com/k2-fsa/sherpa-ncnn/assets/106939577/9538f2e1-8037-4283-a342-12f1e918c9f7)
![微信截图_20240510132443](https://github.com/k2-fsa/sherpa-ncnn/assets/106939577/fc47cfa3-4a08-4a04-a25c-4bd475a9201a)

**Comment by csukuangfj** [comment]
请描述你跑了什么命令，使用了什么工具。
还有，请贴完整的 log. (最好贴文本 log)

**Comment by nihui** [comment]
llvm的bug，上游修复了 https://github.com/llvm/llvm-project/commit/2e4e04c59043
可以临时降级llvm，或者升级最新llvm，或者用 cmake -DNCNN_AVX512BF16=OFF

**Comment by respHr** [comment]
感谢 @nihui 问题已解决。
