### ISSUE TITLE
ios IsFormatSampleRateAndChannelCountValid 错误

### ISSUE THREAD

**Issue by willdla** [k2-fsa/sherpa-ncnn#337]
<img width="1512" alt="image" src="https://github.com/k2-fsa/sherpa-ncnn/assets/93644542/8fb1dc33-5f28-4eec-b9a8-8f542f36db25">

<img width="1512" alt="image" src="https://github.com/k2-fsa/sherpa-ncnn/assets/93644542/ccc1df7e-7227-439f-9e8c-9d67f4ee8c9e">

如图 模拟器运行时会遇到这个错误

https://stackoverflow.com/questions/74516660/ios-app-crashes-with-required-condition-is-false-isformatsamplerateandchannelc

https://stackoverflow.com/questions/60984704/required-condition-is-false-isformatsamplerateandchannelcountvalidformat

谷歌查到的答案云里雾里的..

难道要有真机才可以

大佬知道怎么修复吗

**Comment by csukuangfj** [comment]
我在模拟器里，就可以运行的。你可以看 b 站我们的演示视频。

ios 录音这块，需要你自己解决了。我们对 ios 的开发经验不多。

**Comment by willdla** [comment]
<img width="696" alt="image" src="https://github.com/k2-fsa/sherpa-ncnn/assets/93644542/49191112-787e-4c21-8619-31aa378dc04c">


加一行这个就可以让模拟器跑起来了 但是貌似没法录音

系统没提示有设备在使用录音

xcode 上显示

           AURemoteIO.cpp:1162  failed: -10851 (enable 1, outf< 2 ch,      0 Hz, Float32, deinterleaved> inf< 2 ch,      0 Hz, Float32, deinterleaved>)

点击start后

     AURemoteIO.cpp:1162  failed: -10851 (enable 1, outf< 2 ch,      0 Hz, Float32, deinterleaved> inf< 2 ch,      0 Hz, Float32, deinterleaved>)

           AVAEInternal.h:109   [AVAudioEngineGraph.mm:1397:Initialize: (err = AUGraphParser::InitializeActiveNodesInInputChain(ThisGraph, *GetInputNode())): error -10851

Got an error starting audioEngine: com.apple.coreaudio.avfaudio, Error Domain=com.apple.coreaudio.avfaudio Code=-10851 "(null)" UserInfo={failed call=err = AUGraphParser::InitializeActiveNodesInInputChain(ThisGraph, *GetInputNode())}

ios好垃圾啊 调用个录音都这么麻烦
