### ISSUE TITLE
输入音频和视频文件转文字

### ISSUE THREAD

**Issue by jkm123** [k2-fsa/sherpa-ncnn#347]
是否支持传入一个音频和视频文件，输出文本；

**Comment by csukuangfj** [comment]
支持的，请用
https://github.com/k2-fsa/sherpa-ncnn/tree/master/ffmpeg-examples

**Comment by jkm123** [comment]
怎么移植到Android端呢，有相关的demo不；

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-ncnn/tree/master/android
这里有 demo.


----

https://github.com/k2-fsa/sherpa-ncnn/releases/tag/v2.1.10
这里有编译好的 apk, 你自己可以下载、测试。

**Comment by jkm123** [comment]
感谢！
这个demo是实时语音识别的，我已了解；
我是想问输入：一个音频或视频文件，输出：文本，这种方式在Android端接入的文档或者demo有么；

**Comment by csukuangfj** [comment]
如何读音频文件，或者如何读视频文件，你自己解决，这个不是语音识别框架需要做的事情。

我们提供的 api, 不关注 audio samples 来自哪里。
