### ISSUE TITLE
请问是否有 ncnn 的粤语，方言 model? 

### ISSUE THREAD

**Issue by wingjoezhou** [k2-fsa/sherpa-ncnn#350]
请问如何将 sherpa-onnx-streaming-paraformer-trilingual-zh-cantonese-en (Chinese + Cantonese + English)
这个 onnx model 转成 ncnn  small 可以在 Raspberry Pi 4 上使用？ 

我想使用 粤语，和四川话来 asr， 谢谢。

**Comment by csukuangfj** [comment]
> 请问如何将

这个需要大量的时间。

---


请先用 sherpa-onnx
