### ISSUE TITLE
Python API  或 其他语言 API如何使用这个模型

### ISSUE THREAD

**Issue by Consulting4J** [k2-fsa/sherpa-ncnn#360]
https://huggingface.co/csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17

看它的格式跟其他的都不太一样

标准的都是这样的
    recognizer = sherpa_ncnn.Recognizer(
        tokens="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/tokens.txt",
        encoder_param="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/encoder_jit_trace-pnnx.ncnn.param",
        encoder_bin="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/encoder_jit_trace-pnnx.ncnn.bin",
        decoder_param="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/decoder_jit_trace-pnnx.ncnn.param",
        decoder_bin="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/decoder_jit_trace-pnnx.ncnn.bin",
        joiner_param="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/joiner_jit_trace-pnnx.ncnn.param",
        joiner_bin="./sherpa-ncnn-conv-emformer-transducer-2022-12-06/joiner_jit_trace-pnnx.ncnn.bin",
        num_threads=4,
        hotwords_file="",
        hotwords_score=1.5,
    )

**Comment by csukuangfj** [comment]
文档里没有写的模型，都不支持。

**Comment by Consulting4J** [comment]
有流式识别日语的模型吗，就像这个DEMO中的那个

https://www.bilibili.com/video/BV1p54y1P7Be/

**Comment by csukuangfj** [comment]
@Consulting4J 
支持啦！

<img width="1288" height="834" alt="Image" src="https://github.com/user-attachments/assets/bb012c1d-fe18-4053-bf2c-243b243f39f7" />

请看 #416
