### ISSUE TITLE
how compile to win32 x86 arch

### ISSUE THREAD

**Issue by zhou881117** [k2-fsa/sherpa-ncnn#80]
git clone https://github.com/k2-fsa/sherpa-ncnn
cd sherpa-ncnn
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release -- -m:6

it's not build to x86

**Comment by csukuangfj** [comment]
Could you please show the error logs?

**Comment by csukuangfj** [comment]
We have CI test
https://github.com/k2-fsa/sherpa-ncnn/actions/runs/3931355920/jobs/6722499540
to ensure that `sherpa-ncnn` is able to compile and run on Windows.

**Comment by zhou881117** [comment]
1）cmake  -DCMAKE_GENERATOR_PLATFORM=x86 -DCMAKE_BUILD_TYPE=Release ..

the log:

节点 1 上的项目“D:\k2-fsa_x86\sherpa-ncnn\build\CMakeFiles\3.25.1\VCTargetsPath.vcxproj”(默认目标)。
    D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Debug|Win32。 [D:\k2-fsa_x86\sherpa-ncnn\build\CMakeFiles\3.25.1\VCTargetsPath.vcxproj]
    已完成生成项目“D:\k2-fsa_x86\sherpa-ncnn\build\CMakeFiles\3.25.1\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “D:\k2-fsa_x86\sherpa-ncnn\build\CMakeFiles\3.25.1\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (PrepareForBuild 目标) ->
      D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Debug|Win32。 [D:\k2-fsa_x86\sherpa-ncnn\build\CMakeFiles\3.25.1\VCTargetsPath.vcxproj]



2）cmake  -A Win32 -DCMAKE_BUILD_TYPE=Release ..
    
    when run:  cannot find MSVCP140D.dll
    and vs2019->configuration advanced  ->preferred build tool archtecture : 64-bit(x64)

3) cmake    -DCMAKE_GENERATOR_PLATFORM=x86 -A Win32 -DCMAKE_BUILD_TYPE=Release..
   
the log:
-- Building for: Visual Studio 16 2019
CMake Error: Error: generator platform: Win32
Does not match the platform used previously: x86
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

**Comment by csukuangfj** [comment]
```
cmake --help
```
这个输出什么呢

**Comment by zhou881117** [comment]
cmake --version
cmake version 3.25.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by csukuangfj** [comment]
试试这里的命令：
https://github.com/Tencent/ncnn/blob/master/.github/workflows/windows-x86-cpu.yml#L59
```
        cmake -T ${{ matrix.toolset-version }},host=x64 -A Win32 -DNCNN_BUILD_TESTS=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
```

其中, toolset-version 的值为
```
          - vs-version: vs2015
            toolset-version: v140
            os: windows-2019

          - vs-version: vs2017
            toolset-version: v141
            os: windows-2019

          - vs-version: vs2019
            toolset-version: v142
            os: windows-2022

          - vs-version: vs2022
            toolset-version: v143
            os: windows-2022
```

比如
```bash
cmake -T v141,host=x64 -A Win32 -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release -- -m:6
```

记得先把 build 目录删掉，然后再重新创建 build 目录，然后再跑上面的命令。

删掉原来的 build 目录，这一步，必不可少.

**Comment by zhou881117** [comment]
cmake -T v142,host=x86 -A Win32 -DNCNN_BUILD_TESTS=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..

由于找不到 MSVCP140D.dll

**Comment by zhou881117** [comment]
生成的 sherpa-ncnn.exe  sherpa-ncnn-microphone.exe  是32位的，且有效的。vs32调试有问题，但够用了

**Comment by zhou881117** [comment]
> 试试这里的命令： https://github.com/Tencent/ncnn/blob/master/.github/workflows/windows-x86-cpu.yml#L59
> 
> ```
>         cmake -T ${{ matrix.toolset-version }},host=x64 -A Win32 -DNCNN_BUILD_TESTS=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
> ```
> 
> 其中, toolset-version 的值为
> 
> ```
>           - vs-version: vs2015
>             toolset-version: v140
>             os: windows-2019
> 
>           - vs-version: vs2017
>             toolset-version: v141
>             os: windows-2019
> 
>           - vs-version: vs2019
>             toolset-version: v142
>             os: windows-2022
> 
>           - vs-version: vs2022
>             toolset-version: v143
>             os: windows-2022
> ```
> 
> 比如
> 
> ```shell
> cmake -T v141,host=x64 -A Win32 -DCMAKE_BUILD_TYPE=Release ..
> cmake --build . --config Release -- -m:6
> ```
> 
> 记得先把 build 目录删掉，然后再重新创建 build 目录，然后再跑上面的命令。
> 
> 删掉原来的 build 目录，这一步，必不可少.

host=x64 生成的vs工程可以调试。输出的文件也能正常使用，但对vc有依赖。

**Comment by csukuangfj** [comment]
> host=x64 生成的vs工程可以调试。输出的文件也能正常使用，但对vc有依赖。

去掉 host=x64 之后呢？
