### ISSUE TITLE
how to run the stream Chinese demo?

### ISSUE THREAD

**Issue by jinfagang** [k2-fsa/sherpa-ncnn#82]
./bin/sherpa-ncnn

Usage:
  ./bin/sherpa-ncnn \
    /path/to/tokens.txt \
    /path/to/encoder.ncnn.param \
    /path/to/encoder.ncnn.bin \
    /path/to/decoder.ncnn.param \
    /path/to/decoder.ncnn.bin \
    /path/to/joiner.ncnn.param \
    /path/to/joiner.ncnn.bin \
    /path/to/foo.wav [num_threads] [decode_method, can be greedy_search/modified_beam_search]

I didn't know where to download param and bin?

also the token.txt? Does this can be packaged in a zip and included in github release page?

**Comment by jinfagang** [comment]
ok, I downloaded the model, but don't how to run in stream? I want it listen to my microphones of my mac

**Comment by csukuangfj** [comment]
Have you found the solution from the doc?

**Comment by csukuangfj** [comment]
you can either use the binary 

sherpa-ncnn-microphone 

or the Python API.
