### ISSUE TITLE
Will it consider support MNN or onnxruntime support?

### ISSUE THREAD

**Issue by lucasjinreal** [k2-fsa/sherpa-ncnn#83]

**Comment by csukuangfj** [comment]
onnxruntime is supported in sherpa-onnx.


There is no plan to support mnn in the near future as we don't have much resource to do that.

**Comment by jinfagang** [comment]
I didn't see a streaming version or microphone version in onnxruntime, does it able to use out-of-box as ncnn?

**Comment by csukuangfj** [comment]
> I didn't see a streaming version or microphone version in onnxruntime, does it able to use out-of-box as ncnn?

We will add streaming support to sherpa-onnx after the Chinese New Year.

**Comment by csukuangfj** [comment]
> I didn't see a streaming version or microphone version in onnxruntime, does it able to use out-of-box as ncnn?

It's supported now.
