### ISSUE TITLE
run sherpa-ncnn error:layer LSTM2 not exists or registered

### ISSUE THREAD

**Issue by crmlei** [k2-fsa/sherpa-ncnn#93]
在Linux上编译成功，也下载模型参数后，运行：
./sherpa-ncnn \
 ./model/chn/tokens.txt \
 ./model/chn/encoder_jit_trace-epoch-11-avg-2-pnnx.ncnn.param \
 ./model/chn/encoder_jit_trace-epoch-11-avg-2-pnnx.ncnn.bin \
 ./model/chn/decoder_jit_trace-epoch-11-avg-2-pnnx.ncnn.param \
 ./model/chn/decoder_jit_trace-epoch-11-avg-2-pnnx.ncnn.bin \
 ./model/chn/joiner_jit_trace-epoch-11-avg-2-pnnx.ncnn.param \
 ./model/chn/joiner_jit_trace-epoch-11-avg-2-pnnx.ncnn.bin \
 ./model/chn/test_wavs/0.wav

显示错误:  layer LSTM2 not exists or registered  
程序 core dump了

想问下可能是什么原因，谢谢

**Comment by csukuangfj** [comment]
使用方法，请参考具体的文档.

**Comment by csukuangfj** [comment]
![Screenshot 2023-01-31 at 21 24 10](https://user-images.githubusercontent.com/5284924/215772574-fc2836d9-f4a7-4f99-8b11-094a3337ca54.png)

**Comment by crmlei** [comment]
谢谢，OK了（看了之情老的文档）。

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/lstm-transducer-models.html#id1

具体的命令，我们都给你在文档里写好了。你直接 copy & paste 就够了.

```bash
./build/bin/sherpa-ncnn \
 ./sherpa-ncnn-2022-09-30/tokens.txt \
 ./sherpa-ncnn-2022-09-30/encoder_jit_trace-v2-epoch-11-avg-2-pnnx.ncnn.param \
 ./sherpa-ncnn-2022-09-30/encoder_jit_trace-v2-epoch-11-avg-2-pnnx.ncnn.bin \
 ./sherpa-ncnn-2022-09-30/decoder_jit_trace-v2-epoch-11-avg-2-pnnx.ncnn.param \
 ./sherpa-ncnn-2022-09-30/decoder_jit_trace-v2-epoch-11-avg-2-pnnx.ncnn.bin \
 ./sherpa-ncnn-2022-09-30/joiner_jit_trace-v2-epoch-11-avg-2-pnnx.ncnn.param \
 ./sherpa-ncnn-2022-09-30/joiner_jit_trace-v2-epoch-11-avg-2-pnnx.ncnn.bin \
 ./sherpa-ncnn-2022-09-30/test_wavs/0.wav
```

copy & paste, 就不会出现现在你这个错误了。

**Comment by csukuangfj** [comment]
> 谢谢，OK了（看了之情老的文档）。

我把旧模型删掉算了

**Comment by crmlei** [comment]
谢谢。

**Comment by csukuangfj** [comment]
已删掉 outdated 模型。
