### ISSUE TITLE
question about beam search in sherpa-ncnn

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/sherpa-ncnn#97]
`modified_beam_search` in sherpa-ncnn has 3 loops, means the time complexity is `O(T*beam*beam)`, while in icefall, the time complexity is `O(T*beam)` ?
https://github.com/k2-fsa/sherpa-ncnn/blob/6b7072b3d9ac8756972d12bad741508d41546bcc/sherpa-ncnn/csrc/modified-beam-search-decoder.cc#L58-L78
[modified_beam_search in icefall](https://github.com/k2-fsa/icefall/blob/bffce413f07d938e35d69d5eb2f360c7ff842502/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L1142) or [modified_beam_search in icefall](https://github.com/k2-fsa/icefall/blob/bffce413f07d938e35d69d5eb2f360c7ff842502/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L1006)

**Comment by csukuangfj** [comment]
Thanks for pointing it out.  Yes, you are right.

**Comment by csukuangfj** [comment]
The fix is to build a 2-D decoder_input to represent the current 1-D decoder_input and run the joiner only once.

Contribution from the community is highly appreciated.

**Comment by kobenaxie** [comment]
> The fix is to build a 2-D decoder_input to represent the current 1-D decoder_input and run the joiner only once.
> 
> Contribution from the community is highly appreciated.

yes ! Then sherpa-ncnn  will be faster.
